package dev.matito.forceItem.util;

import org.bukkit.Material;
import org.bukkit.entity.Item;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public enum ItemEntry {
	// Overworld
	DIRT("Dirt", Dimension.OVERWORLD, 0),
	GRASS_BLOCK("Grass Block", Dimension.OVERWORLD, 0),
	COBBLESTONE("Cobblestone", Dimension.OVERWORLD, 0),
	OAK_LOG("Oak Log", Dimension.OVERWORLD, 0),
	OAK_PLANKS("Oak Planks", Dimension.OVERWORLD, 0),
	OAK_SAPLING("Oak Sapling", Dimension.OVERWORLD, 0),
	OAK_LEAVES("Oak Leaves", Dimension.OVERWORLD, 0),
	OAK_BOAT("Oak Boat", Dimension.OVERWORLD, 0),
	OAK_WOOD("Oak Wood", Dimension.OVERWORLD, 0),
	OAK_FENCE("Oak Fence", Dimension.OVERWORLD, 0),
	OAK_FENCE_GATE("Oak Fence Gate", Dimension.OVERWORLD, 0),
	OAK_DOOR("Oak Door", Dimension.OVERWORLD, 0),
	OAK_TRAPDOOR("Oak Trapdoor", Dimension.OVERWORLD, 0),
	OAK_SLAB("Oak Slab", Dimension.OVERWORLD, 0),
	OAK_STAIRS("Oak Stairs", Dimension.OVERWORLD, 0),
	OAK_BUTTON("Oak Button", Dimension.OVERWORLD, 0),
	OAK_PRESSURE_PLATE("Oak Pressure Plate", Dimension.OVERWORLD, 0),
	SPRUCE_LOG("Spruce Log", Dimension.OVERWORLD, 0),
	SPRUCE_PLANKS("Spruce Planks", Dimension.OVERWORLD, 0),
	SPRUCE_SAPLING("Spruce Sapling", Dimension.OVERWORLD, 0),
	SPRUCE_LEAVES("Spruce Leaves", Dimension.OVERWORLD, 0),
	SPRUCE_BOAT("Spruce Boat", Dimension.OVERWORLD, 0),
	SPRUCE_WOOD("Spruce Wood", Dimension.OVERWORLD, 0),
	SPRUCE_FENCE("Spruce Fence", Dimension.OVERWORLD, 0),
	SPRUCE_FENCE_GATE("Spruce Fence Gate", Dimension.OVERWORLD, 0),
	SPRUCE_DOOR("Spruce Door", Dimension.OVERWORLD, 0),
	SPRUCE_TRAPDOOR("Spruce Trapdoor", Dimension.OVERWORLD, 0),
	SPRUCE_SLAB("Spruce Slab", Dimension.OVERWORLD, 0),
	SPRUCE_STAIRS("Spruce Stairs", Dimension.OVERWORLD, 0),
	SPRUCE_BUTTON("Spruce Button", Dimension.OVERWORLD, 0),
	SPRUCE_PRESSURE_PLATE("Spruce Pressure Plate", Dimension.OVERWORLD, 0),
	BIRCH_LOG("Birch Log", Dimension.OVERWORLD, 0),
	BIRCH_PLANKS("Birch Planks", Dimension.OVERWORLD, 0),
	BIRCH_SAPLING("Birch Sapling", Dimension.OVERWORLD, 0),
	BIRCH_LEAVES("Birch Leaves", Dimension.OVERWORLD, 0),
	BIRCH_BOAT("Birch Boat", Dimension.OVERWORLD, 0),
	BIRCH_WOOD("Birch Wood", Dimension.OVERWORLD, 0),
	BIRCH_FENCE("Birch Fence", Dimension.OVERWORLD, 0),
	BIRCH_FENCE_GATE("Birch Fence Gate", Dimension.OVERWORLD, 0),
	BIRCH_DOOR("Birch Door", Dimension.OVERWORLD, 0),
	BIRCH_TRAPDOOR("Birch Trapdoor", Dimension.OVERWORLD, 0),
	BIRCH_SLAB("Birch Slab", Dimension.OVERWORLD, 0),
	BIRCH_STAIRS("Birch Stairs", Dimension.OVERWORLD, 0),
	BIRCH_BUTTON("Birch Button", Dimension.OVERWORLD, 0),
	BIRCH_PRESSURE_PLATE("Birch Pressure Plate", Dimension.OVERWORLD, 0),
	JUNGLE_LOG("Jungle Log", Dimension.OVERWORLD, 0),
	JUNGLE_PLANKS("Jungle Planks", Dimension.OVERWORLD, 0),
	JUNGLE_SAPLING("Jungle Sapling", Dimension.OVERWORLD, 0),
	JUNGLE_LEAVES("Jungle Leaves", Dimension.OVERWORLD, 0),
	JUNGLE_BOAT("Jungle Boat", Dimension.OVERWORLD, 0),
	JUNGLE_WOOD("Jungle Wood", Dimension.OVERWORLD, 0),
	JUNGLE_FENCE("Jungle Fence", Dimension.OVERWORLD, 0),
	JUNGLE_FENCE_GATE("Jungle Fence Gate", Dimension.OVERWORLD, 0),
	JUNGLE_DOOR("Jungle Door", Dimension.OVERWORLD, 0),
	JUNGLE_TRAPDOOR("Jungle Trapdoor", Dimension.OVERWORLD, 0),
	JUNGLE_SLAB("Jungle Slab", Dimension.OVERWORLD, 0),
	JUNGLE_STAIRS("Jungle Stairs", Dimension.OVERWORLD, 0),
	JUNGLE_BUTTON("Jungle Button", Dimension.OVERWORLD, 0),
	JUNGLE_PRESSURE_PLATE("Jungle Pressure Plate", Dimension.OVERWORLD, 0),
	ACACIA_LOG("Acacia Log", Dimension.OVERWORLD, 0),
	ACACIA_PLANKS("Acacia Planks", Dimension.OVERWORLD, 0),
	ACACIA_SAPLING("Acacia Sapling", Dimension.OVERWORLD, 0),
	ACACIA_LEAVES("Acacia Leaves", Dimension.OVERWORLD, 0),
	ACACIA_BOAT("Acacia Boat", Dimension.OVERWORLD, 0),
	ACACIA_WOOD("Acacia Wood", Dimension.OVERWORLD, 0),
	ACACIA_FENCE("Acacia Fence", Dimension.OVERWORLD, 0),
	ACACIA_FENCE_GATE("Acacia Fence Gate", Dimension.OVERWORLD, 0),
	ACACIA_DOOR("Acacia Door", Dimension.OVERWORLD, 0),
	ACACIA_TRAPDOOR("Acacia Trapdoor", Dimension.OVERWORLD, 0),
	ACACIA_SLAB("Acacia Slab", Dimension.OVERWORLD, 0),
	ACACIA_STAIRS("Acacia Stairs", Dimension.OVERWORLD, 0),
	ACACIA_BUTTON("Acacia Button", Dimension.OVERWORLD, 0),
	ACACIA_PRESSURE_PLATE("Acacia Pressure Plate", Dimension.OVERWORLD, 0),
	DARK_OAK_LOG("Dark Oak Log", Dimension.OVERWORLD, 0),
	DARK_OAK_PLANKS("Dark Oak Planks", Dimension.OVERWORLD, 0),
	DARK_OAK_SAPLING("Dark Oak Sapling", Dimension.OVERWORLD, 0),
	DARK_OAK_LEAVES("Dark Oak Leaves", Dimension.OVERWORLD, 0),
	DARK_OAK_BOAT("Dark Oak Boat", Dimension.OVERWORLD, 0),
	DARK_OAK_WOOD("Dark Oak Wood", Dimension.OVERWORLD, 0),
	DARK_OAK_FENCE("Dark Oak Fence", Dimension.OVERWORLD, 0),
	DARK_OAK_FENCE_GATE("Dark Oak Fence Gate", Dimension.OVERWORLD, 0),
	DARK_OAK_DOOR("Dark Oak Door", Dimension.OVERWORLD, 0),
	DARK_OAK_TRAPDOOR("Dark Oak Trapdoor", Dimension.OVERWORLD, 0),
	DARK_OAK_SLAB("Dark Oak Slab", Dimension.OVERWORLD, 0),
	DARK_OAK_STAIRS("Dark Oak Stairs", Dimension.OVERWORLD, 0),
	DARK_OAK_BUTTON("Dark Oak Button", Dimension.OVERWORLD, 0),
	DARK_OAK_PRESSURE_PLATE("Dark Oak Pressure Plate", Dimension.OVERWORLD, 0),
	MANGROVE_LOG("Mangrove Log", Dimension.OVERWORLD, 0),
	MANGROVE_PLANKS("Mangrove Planks", Dimension.OVERWORLD, 0),
	MANGROVE_PROPAGULE("Mangrove Propagule", Dimension.OVERWORLD, 0),
	MANGROVE_LEAVES("Mangrove Leaves", Dimension.OVERWORLD, 0),
	MANGROVE_BOAT("Mangrove Boat", Dimension.OVERWORLD, 0),
	MANGROVE_WOOD("Mangrove Wood", Dimension.OVERWORLD, 0),
	MANGROVE_FENCE("Mangrove Fence", Dimension.OVERWORLD, 0),
	MANGROVE_FENCE_GATE("Mangrove Fence Gate", Dimension.OVERWORLD, 0),
	MANGROVE_DOOR("Mangrove Door", Dimension.OVERWORLD, 0),
	MANGROVE_TRAPDOOR("Mangrove Trapdoor", Dimension.OVERWORLD, 0),
	MANGROVE_SLAB("Mangrove Slab", Dimension.OVERWORLD, 0),
	MANGROVE_STAIRS("Mangrove Stairs", Dimension.OVERWORLD, 0),
	MANGROVE_BUTTON("Mangrove Button", Dimension.OVERWORLD, 0),
	MANGROVE_PRESSURE_PLATE("Mangrove Pressure Plate", Dimension.OVERWORLD, 0),
	BAMBOO_BLOCK("Block of Bamboo", Dimension.OVERWORLD, 0),
	BAMBOO_PLANKS("Bamboo Planks", Dimension.OVERWORLD, 0),
	BAMBOO_MOSAIC("Bamboo Mosaic", Dimension.OVERWORLD, 0),
	BAMBOO_RAFT("Bamboo Raft", Dimension.OVERWORLD, 0),
	BAMBOO_DOOR("Bamboo Door", Dimension.OVERWORLD, 0),
	BAMBOO_TRAPDOOR("Bamboo Trapdoor", Dimension.OVERWORLD, 0),
	BAMBOO_SLAB("Bamboo Slab", Dimension.OVERWORLD, 0),
	BAMBOO_MOSAIC_SLAB("Bamboo Mosaic Slab", Dimension.OVERWORLD, 0),
	BAMBOO_STAIRS("Bamboo Stairs", Dimension.OVERWORLD, 0),
	BAMBOO_MOSAIC_STAIRS("Bamboo Mosaic Stairs", Dimension.OVERWORLD, 0),
	BAMBOO_BUTTON("Bamboo Button", Dimension.OVERWORLD, 0),
	BAMBOO_PRESSURE_PLATE("Bamboo Pressure Plate", Dimension.OVERWORLD, 0),
	STRIPPED_OAK_LOG("Stripped Oak Log", Dimension.OVERWORLD, 0),
	STRIPPED_OAK_WOOD("Stripped Oak Wood", Dimension.OVERWORLD, 0),
	STRIPPED_SPRUCE_LOG("Stripped Spruce Log", Dimension.OVERWORLD, 0),
	STRIPPED_SPRUCE_WOOD("Stripped Spruce Wood", Dimension.OVERWORLD, 0),
	STRIPPED_BIRCH_LOG("Stripped Birch Log", Dimension.OVERWORLD, 0),
	STRIPPED_BIRCH_WOOD("Stripped Birch Wood", Dimension.OVERWORLD, 0),
	STRIPPED_JUNGLE_LOG("Stripped Jungle Log", Dimension.OVERWORLD, 0),
	STRIPPED_JUNGLE_WOOD("Stripped Jungle Wood", Dimension.OVERWORLD, 0),
	STRIPPED_ACACIA_LOG("Stripped Acacia Log", Dimension.OVERWORLD, 0),
	STRIPPED_ACACIA_WOOD("Stripped Acacia Wood", Dimension.OVERWORLD, 0),
	STRIPPED_DARK_OAK_LOG("Stripped Dark Oak Log", Dimension.OVERWORLD, 0),
	STRIPPED_DARK_OAK_WOOD("Stripped Dark Oak Wood", Dimension.OVERWORLD, 0),
	STRIPPED_MANGROVE_LOG("Stripped Mangrove Log", Dimension.OVERWORLD, 0),
	STRIPPED_MANGROVE_WOOD("Stripped Mangrove Wood", Dimension.OVERWORLD, 0),
	STRIPPED_BAMBOO_BLOCK("Block of Stripped Bamboo", Dimension.OVERWORLD, 0),
	SAND("Sand", Dimension.OVERWORLD, 0),
	GRAVEL("Gravel", Dimension.OVERWORLD, 0),
	CLAY("Clay", Dimension.OVERWORLD, 0),
	CLAY_BALL("Clay Ball", Dimension.OVERWORLD, 0),
	SUGAR_CANE("Sugar Cane", Dimension.OVERWORLD, 0),
	WHEAT_SEEDS("Wheat Seeds", Dimension.OVERWORLD, 0),
	WHEAT("Wheat", Dimension.OVERWORLD, 0),
	CARROT("Carrot", Dimension.OVERWORLD, 0),
	POTATO("Potato", Dimension.OVERWORLD, 0),
	BEETROOT_SEEDS("Beetroot Seeds", Dimension.OVERWORLD, 0),
	BEETROOT("Beetroot", Dimension.OVERWORLD, 0),
	PUMPKIN_SEEDS("Pumpkin Seeds", Dimension.OVERWORLD, 0),
	PUMPKIN("Pumpkin", Dimension.OVERWORLD, 0),
	MELON_SEEDS("Melon Seeds", Dimension.OVERWORLD, 0),
	MELON_SLICE("Melon Slice", Dimension.OVERWORLD, 0),
	MELON("Melon", Dimension.OVERWORLD, 0),
	COCOA_BEANS("Cocoa Beans", Dimension.OVERWORLD, 0),
	APPLE("Apple", Dimension.OVERWORLD, 0),
	SWEET_BERRIES("Sweet Berries", Dimension.OVERWORLD, 0),
	BONE("Bone", Dimension.OVERWORLD, 0),
	BONE_MEAL("Bone Meal", Dimension.OVERWORLD, 0),
	STRING("String", Dimension.OVERWORLD, 0),
	FEATHER("Feather", Dimension.OVERWORLD, 0),
	ROTTEN_FLESH("Rotten Flesh", Dimension.OVERWORLD, 0),
	SPIDER_EYE("Spider Eye", Dimension.OVERWORLD, 0),
	GUNPOWDER("Gunpowder", Dimension.OVERWORLD, 0),
	COAL_ORE("Coal Ore", Dimension.OVERWORLD, 0),
	COAL("Coal", Dimension.OVERWORLD, 0),
	RAW_COPPER("Raw Copper", Dimension.OVERWORLD, 0),
	COPPER_ORE("Copper Ore", Dimension.OVERWORLD, 0),
	RAW_IRON("Raw Iron", Dimension.OVERWORLD, 0),
	IRON_ORE("Iron Ore", Dimension.OVERWORLD, 0),
	RAW_GOLD("Raw Gold", Dimension.OVERWORLD, 0),
	GOLD_ORE("Gold Ore", Dimension.OVERWORLD, 0),
	LAPIS_LAZULI_ORE("Lapis Lazuli Ore", Dimension.OVERWORLD, 0),
	LAPIS_LAZULI("Lapis Lazuli", Dimension.OVERWORLD, 0),
	REDSTONE_ORE("Redstone Ore", Dimension.OVERWORLD, 0),
	REDSTONE_DUST("Redstone Dust", Dimension.OVERWORLD, 0),
	DIAMOND_ORE("Diamond Ore", Dimension.OVERWORLD, 0),
	DIAMOND("Diamond", Dimension.OVERWORLD, 0),
	EMERALD_ORE("Emerald Ore", Dimension.OVERWORLD, 0),
	EMERALD("Emerald", Dimension.OVERWORLD, 0),
	AMETHYST_SHARD("Amethyst Shard", Dimension.OVERWORLD, 0),
	SMALL_AMETHYST_BUD("Small Amethyst Bud", Dimension.OVERWORLD, 0),
	MEDIUM_AMETHYST_BUD("Medium Amethyst Bud", Dimension.OVERWORLD, 0),
	LARGE_AMETHYST_BUD("Large Amethyst Bud", Dimension.OVERWORLD, 0),
	AMETHYST_CLUSTER("Amethyst Cluster", Dimension.OVERWORLD, 0),
	BLOCK_OF_AMETHYST("Block of Amethyst", Dimension.OVERWORLD, 0),
	CALCITE("Calcite", Dimension.OVERWORLD, 0),
	TUFF("Tuff", Dimension.OVERWORLD, 0),
	DIORITE("Diorite", Dimension.OVERWORLD, 0),
	ANDESITE("Andesite", Dimension.OVERWORLD, 0),
	GRANITE("Granite", Dimension.OVERWORLD, 0),
	STONE("Stone", Dimension.OVERWORLD, 0),
	SANDSTONE("Sandstone", Dimension.OVERWORLD, 0),
	RED_SAND("Red Sand", Dimension.OVERWORLD, 0),
	RED_SANDSTONE("Red Sandstone", Dimension.OVERWORLD, 0),
	TERRACOTTA("Terracotta", Dimension.OVERWORLD, 0),
	BROWN_MUSHROOM("Brown Mushroom", Dimension.OVERWORLD, 0),
	RED_MUSHROOM("Red Mushroom", Dimension.OVERWORLD, 0),
	LILY_PAD("Lily Pad", Dimension.OVERWORLD, 0),
	VINES("Vines", Dimension.OVERWORLD, 0),
	CACTUS("Cactus", Dimension.OVERWORLD, 0),
	SEAGRASS("Seagrass", Dimension.OVERWORLD, 0),
	KELP("Kelp", Dimension.OVERWORLD, 0),
	DRIED_KELP("Dried Kelp", Dimension.OVERWORLD, 0),
	DRIED_KELP_BLOCK("Dried Kelp Block", Dimension.OVERWORLD, 0),
	SNOWBALL("Snowball", Dimension.OVERWORLD, 0),
	SNOW("Snow", Dimension.OVERWORLD, 0),
	SNOW_BLOCK("Snow Block", Dimension.OVERWORLD, 0),
	ICE("Ice", Dimension.OVERWORLD, 0),
	GLASS("Glass", Dimension.OVERWORLD, 0),
	GLASS_PANE("Glass Pane", Dimension.OVERWORLD, 0),
	SUGAR("Sugar", Dimension.OVERWORLD, 0),
	ARROW("Arrow", Dimension.OVERWORLD, 0),
	STICK("Stick", Dimension.OVERWORLD, 0),
	FLINT("Flint", Dimension.OVERWORLD, 0),
	BOWL("Bowl", Dimension.OVERWORLD, 0),
	EGG("Egg", Dimension.OVERWORLD, 0),
	BREAD("Bread", Dimension.OVERWORLD, 0),
	RAW_CHICKEN("Raw Chicken", Dimension.OVERWORLD, 0),
	RAW_PORKCHOP("Raw Porkchop", Dimension.OVERWORLD, 0),
	RAW_BEEF("Raw Beef", Dimension.OVERWORLD, 0),
	RAW_MUTTON("Raw Mutton", Dimension.OVERWORLD, 0),
	RAW_RABBIT("Raw Rabbit", Dimension.OVERWORLD, 0),
	RAW_COD("Raw Cod", Dimension.OVERWORLD, 0),
	RAW_SALMON("Raw Salmon", Dimension.OVERWORLD, 0),
	PUFFERFISH("Pufferfish", Dimension.OVERWORLD, 0),
	TROPICAL_FISH("Tropical Fish", Dimension.OVERWORLD, 0),
	COOKIE("Cookie", Dimension.OVERWORLD, 0),
	CAKE("Cake", Dimension.OVERWORLD, 0),
	DANDELION("Dandelion", Dimension.OVERWORLD, 0),
	POPPY("Poppy", Dimension.OVERWORLD, 0),
	BLUE_ORCHID("Blue Orchid", Dimension.OVERWORLD, 0),
	ALLIUM("Allium", Dimension.OVERWORLD, 0),
	AZURE_BLUET("Azure Bluet", Dimension.OVERWORLD, 0),
	RED_TULIP("Red Tulip", Dimension.OVERWORLD, 0),
	ORANGE_TULIP("Orange Tulip", Dimension.OVERWORLD, 0),
	WHITE_TULIP("White Tulip", Dimension.OVERWORLD, 0),
	PINK_TULIP("Pink Tulip", Dimension.OVERWORLD, 0),
	OXEYE_DAISY("Oxeye Daisy", Dimension.OVERWORLD, 0),
	CORNFLOWER("Cornflower", Dimension.OVERWORLD, 0),
	LILY_OF_THE_VALLEY("Lily of the Valley", Dimension.OVERWORLD, 0),
	WITHER_ROSE("Wither Rose", Dimension.OVERWORLD, 0),
	SUNFLOWER("Sunflower", Dimension.OVERWORLD, 0),
	LILAC("Lilac", Dimension.OVERWORLD, 0),
	ROSE_BUSH("Rose Bush", Dimension.OVERWORLD, 0),
	PEONY("Peony", Dimension.OVERWORLD, 0),
	AZALEA("Azalea", Dimension.OVERWORLD, 0),
	AZALEA_LEAVES("Azalea Leaves", Dimension.OVERWORLD, 0),
	FLOWERING_AZALEA("Flowering Azalea", Dimension.OVERWORLD, 0),
	FLOWERING_AZALEA_LEAVES("Flowering Azalea Leaves", Dimension.OVERWORLD, 0),
	SHORT_GRASS("Short Grass (Grass)", Dimension.OVERWORLD, 0),
	FERN("Fern", Dimension.OVERWORLD, 0),
	LARGE_FERN("Large Fern", Dimension.OVERWORLD, 0),
	SEA_PICKLE("Sea Pickle", Dimension.OVERWORLD, 0),
	TUBE_CORAL("Tube Coral", Dimension.OVERWORLD, 0),
	BRAIN_CORAL("Brain Coral", Dimension.OVERWORLD, 0),
	BUBBLE_CORAL("Bubble Coral", Dimension.OVERWORLD, 0),
	FIRE_CORAL("Fire Coral", Dimension.OVERWORLD, 0),
	HORN_CORAL("Horn Coral", Dimension.OVERWORLD, 0),
	TUBE_CORAL_FAN("Tube Coral Fan", Dimension.OVERWORLD, 0),
	BRAIN_CORAL_FAN("Brain Coral Fan", Dimension.OVERWORLD, 0),
	BUBBLE_CORAL_FAN("Bubble Coral Fan", Dimension.OVERWORLD, 0),
	FIRE_CORAL_FAN("Fire Coral Fan", Dimension.OVERWORLD, 0),
	HORN_CORAL_FAN("Horn Coral Fan", Dimension.OVERWORLD, 0),
	TUBE_CORAL_BLOCK("Tube Coral Block", Dimension.OVERWORLD, 0),
	BRAIN_CORAL_BLOCK("Brain Coral Block", Dimension.OVERWORLD, 0),
	BUBBLE_CORAL_BLOCK("Bubble Coral Block", Dimension.OVERWORLD, 0),
	FIRE_CORAL_BLOCK("Fire Coral Block", Dimension.OVERWORLD, 0),
	HORN_CORAL_BLOCK("Horn Coral Block", Dimension.OVERWORLD, 0),
	DEAD_TUBE_CORAL("Dead Tube Coral", Dimension.OVERWORLD, 0),
	DEAD_BRAIN_CORAL("Dead Brain Coral", Dimension.OVERWORLD, 0),
	DEAD_BUBBLE_CORAL("Dead Bubble Coral", Dimension.OVERWORLD, 0),
	DEAD_FIRE_CORAL("Dead Fire Coral", Dimension.OVERWORLD, 0),
	DEAD_HORN_CORAL("Dead Horn Coral", Dimension.OVERWORLD, 0),
	DEAD_TUBE_CORAL_FAN("Dead Tube Coral Fan", Dimension.OVERWORLD, 0),
	DEAD_BRAIN_CORAL_FAN("Dead Brain Coral Fan", Dimension.OVERWORLD, 0),
	DEAD_BUBBLE_CORAL_FAN("Dead Bubble Coral Fan", Dimension.OVERWORLD, 0),
	DEAD_FIRE_CORAL_FAN("Dead Fire Coral Fan", Dimension.OVERWORLD, 0),
	DEAD_HORN_CORAL_FAN("Dead Horn Coral Fan", Dimension.OVERWORLD, 0),
	DEAD_TUBE_CORAL_BLOCK("Dead Tube Coral Block", Dimension.OVERWORLD, 0),
	DEAD_BRAIN_CORAL_BLOCK("Dead Brain Coral Block", Dimension.OVERWORLD, 0),
	DEAD_BUBBLE_CORAL_BLOCK("Dead Bubble Coral Block", Dimension.OVERWORLD, 0),
	DEAD_FIRE_CORAL_BLOCK("Dead Fire Coral Block", Dimension.OVERWORLD, 0),
	DEAD_HORN_CORAL_BLOCK("Dead Horn Coral Block", Dimension.OVERWORLD, 0),
	GRANITE_SLAB("Granite Slab", Dimension.OVERWORLD, 0),
	GRANITE_STAIRS("Granite Stairs", Dimension.OVERWORLD, 0),
	GRANITE_WALL("Granite Wall", Dimension.OVERWORLD, 0),
	DIORITE_SLAB("Diorite Slab", Dimension.OVERWORLD, 0),
	DIORITE_STAIRS("Diorite Stairs", Dimension.OVERWORLD, 0),
	DIORITE_WALL("Diorite Wall", Dimension.OVERWORLD, 0),
	ANDESITE_SLAB("Andesite Slab", Dimension.OVERWORLD, 0),
	ANDESITE_STAIRS("Andesite Stairs", Dimension.OVERWORLD, 0),
	ANDESITE_WALL("Andesite Wall", Dimension.OVERWORLD, 0),
	STONE_SLAB("Stone Slab", Dimension.OVERWORLD, 0),
	STONE_STAIRS("Stone Stairs", Dimension.OVERWORLD, 0),
	COBBLESTONE_SLAB("Cobblestone Slab", Dimension.OVERWORLD, 0),
	COBBLESTONE_STAIRS("Cobblestone Stairs", Dimension.OVERWORLD, 0),
	COBBLESTONE_WALL("Cobblestone Wall", Dimension.OVERWORLD, 0),
	BRICKS("Bricks", Dimension.OVERWORLD, 0),
	BRICK_SLAB("Brick Slab", Dimension.OVERWORLD, 0),
	BRICK_STAIRS("Brick Stairs", Dimension.OVERWORLD, 0),
	BRICK_WALL("Brick Wall", Dimension.OVERWORLD, 0),
	STONE_BRICKS("Stone Bricks", Dimension.OVERWORLD, 0),
	STONE_BRICK_SLAB("Stone Brick Slab", Dimension.OVERWORLD, 0),
	STONE_BRICK_STAIRS("Stone Brick Stairs", Dimension.OVERWORLD, 0),
	STONE_BRICK_WALL("Stone Brick Wall", Dimension.OVERWORLD, 0),
	SANDSTONE_SLAB("Sandstone Slab", Dimension.OVERWORLD, 0),
	SANDSTONE_STAIRS("Sandstone Stairs", Dimension.OVERWORLD, 0),
	SANDSTONE_WALL("Sandstone Wall", Dimension.OVERWORLD, 0),
	CUT_SANDSTONE("Cut Sandstone", Dimension.OVERWORLD, 0),
	CUT_SANDSTONE_SLAB("Cut Sandstone Slab", Dimension.OVERWORLD, 0),
	RED_SANDSTONE_SLAB("Red Sandstone Slab", Dimension.OVERWORLD, 0),
	RED_SANDSTONE_STAIRS("Red Sandstone Stairs", Dimension.OVERWORLD, 0),
	RED_SANDSTONE_WALL("Red Sandstone Wall", Dimension.OVERWORLD, 0),
	CUT_RED_SANDSTONE("Cut Red Sandstone", Dimension.OVERWORLD, 0),
	CUT_RED_SANDSTONE_SLAB("Cut Red Sandstone Slab", Dimension.OVERWORLD, 0),
	SMOOTH_STONE("Smooth Stone", Dimension.OVERWORLD, 0),
	SMOOTH_STONE_SLAB("Smooth Stone Slab", Dimension.OVERWORLD, 0),
	SMOOTH_SANDSTONE("Smooth Sandstone", Dimension.OVERWORLD, 0),
	SMOOTH_SANDSTONE_SLAB("Smooth Sandstone Slab", Dimension.OVERWORLD, 0),
	SMOOTH_SANDSTONE_STAIRS("Smooth Sandstone Stairs", Dimension.OVERWORLD, 0),
	SMOOTH_RED_SANDSTONE("Smooth Red Sandstone", Dimension.OVERWORLD, 0),
	SMOOTH_RED_SANDSTONE_SLAB("Smooth Red Sandstone Slab", Dimension.OVERWORLD, 0),
	SMOOTH_RED_SANDSTONE_STAIRS("Smooth Red Sandstone Stairs", Dimension.OVERWORLD, 0),
	POLISHED_GRANITE("Polished Granite", Dimension.OVERWORLD, 0),
	POLISHED_GRANITE_SLAB("Polished Granite Slab", Dimension.OVERWORLD, 0),
	POLISHED_GRANITE_STAIRS("Polished Granite Stairs", Dimension.OVERWORLD, 0),
	POLISHED_DIORITE("Polished Diorite", Dimension.OVERWORLD, 0),
	POLISHED_DIORITE_SLAB("Polished Diorite Slab", Dimension.OVERWORLD, 0),
	POLISHED_DIORITE_STAIRS("Polished Diorite Stairs", Dimension.OVERWORLD, 0),
	POLISHED_ANDESITE("Polished Andesite", Dimension.OVERWORLD, 0),
	POLISHED_ANDESITE_SLAB("Polished Andesite Slab", Dimension.OVERWORLD, 0),
	POLISHED_ANDESITE_STAIRS("Polished Andesite Stairs", Dimension.OVERWORLD, 0),
	CHISELED_SANDSTONE("Chiseled Sandstone", Dimension.OVERWORLD, 0),
	CHISELED_RED_SANDSTONE("Chiseled Red Sandstone", Dimension.OVERWORLD, 0),
	CHISELED_STONE_BRICKS("Chiseled Stone Bricks", Dimension.OVERWORLD, 0),
	MOSSY_COBBLESTONE("Mossy Cobblestone", Dimension.OVERWORLD, 0),
	MOSSY_COBBLESTONE_SLAB("Mossy Cobblestone Slab", Dimension.OVERWORLD, 0),
	MOSSY_COBBLESTONE_STAIRS("Mossy Cobblestone Stairs", Dimension.OVERWORLD, 0),
	MOSSY_COBBLESTONE_WALL("Mossy Cobblestone Wall", Dimension.OVERWORLD, 0),
	MOSSY_STONE_BRICKS("Mossy Stone Bricks", Dimension.OVERWORLD, 0),
	MOSSY_STONE_BRICK_SLAB("Mossy Stone Brick Slab", Dimension.OVERWORLD, 0),
	MOSSY_STONE_BRICK_STAIRS("Mossy Stone Brick Stairs", Dimension.OVERWORLD, 0),
	MOSSY_STONE_BRICK_WALL("Mossy Stone Brick Wall", Dimension.OVERWORLD, 0),
	OBSIDIAN("Obsidian", Dimension.OVERWORLD, 0),
	GLOWSTONE("Glowstone", Dimension.OVERWORLD, 0),
	GLOWSTONE_DUST("Glowstone Dust", Dimension.OVERWORLD, 0),
	ICE_PACKED("Packed Ice", Dimension.OVERWORLD, 0),
	BLUE_ICE("Blue Ice", Dimension.OVERWORLD, 0),
	COARSE_DIRT("Coarse Dirt", Dimension.OVERWORLD, 0),
	ROOTED_DIRT("Rooted Dirt", Dimension.OVERWORLD, 0),
	MUD("Mud", Dimension.OVERWORLD, 0),
	PACKED_MUD("Packed Mud", Dimension.OVERWORLD, 0),
	MUD_BRICKS("Mud Bricks", Dimension.OVERWORLD, 0),
	MUD_BRICK_SLAB("Mud Brick Slab", Dimension.OVERWORLD, 0),
	MUD_BRICK_STAIRS("Mud Brick Stairs", Dimension.OVERWORLD, 0),
	MUD_BRICK_WALL("Mud Brick Wall", Dimension.OVERWORLD, 0),
	MUDDY_MANGROVE_ROOTS("Muddy Mangrove Roots", Dimension.OVERWORLD, 0),
	DRIPSTONE_BLOCK("Dripstone Block", Dimension.OVERWORLD, 0),
	POINTED_DRIPSTONE("Pointed Dripstone", Dimension.OVERWORLD, 0),
	GLOW_LICHEN("Glow Lichen", Dimension.OVERWORLD, 0),
	SCULK_VEIN("Sculk Vein", Dimension.OVERWORLD, 0),
	COBBLED_DEEPSLATE("Cobbled Deepslate", Dimension.OVERWORLD, 0),
	COBBLED_DEEPSLATE_SLAB("Cobbled Deepslate Slab", Dimension.OVERWORLD, 0),
	COBBLED_DEEPSLATE_STAIRS("Cobbled Deepslate Stairs", Dimension.OVERWORLD, 0),
	COBBLED_DEEPSLATE_WALL("Cobbled Deepslate Wall", Dimension.OVERWORLD, 0),
	POLISHED_DEEPSLATE("Polished Deepslate", Dimension.OVERWORLD, 0),
	POLISHED_DEEPSLATE_SLAB("Polished Deepslate Slab", Dimension.OVERWORLD, 0),
	POLISHED_DEEPSLATE_STAIRS("Polished Deepslate Stairs", Dimension.OVERWORLD, 0),
	POLISHED_DEEPSLATE_WALL("Polished Deepslate Wall", Dimension.OVERWORLD, 0),
	DEEPSLATE_BRICKS("Deepslate Bricks", Dimension.OVERWORLD, 0),
	DEEPSLATE_BRICK_SLAB("Deepslate Brick Slab", Dimension.OVERWORLD, 0),
	DEEPSLATE_BRICK_STAIRS("Deepslate Brick Stairs", Dimension.OVERWORLD, 0),
	DEEPSLATE_BRICK_WALL("Deepslate Brick Wall", Dimension.OVERWORLD, 0),
	CRACKED_DEEPSLATE_BRICKS("Cracked Deepslate Bricks", Dimension.OVERWORLD, 0),
	DEEPSLATE_TILES("Deepslate Tiles", Dimension.OVERWORLD, 0),
	DEEPSLATE_TILE_SLAB("Deepslate Tile Slab", Dimension.OVERWORLD, 0),
	DEEPSLATE_TILE_STAIRS("Deepslate Tile Stairs", Dimension.OVERWORLD, 0),
	DEEPSLATE_TILE_WALL("Deepslate Tile Wall", Dimension.OVERWORLD, 0),
	CRACKED_DEEPSLATE_TILES("Cracked Deepslate Tiles", Dimension.OVERWORLD, 0),
	CHISELED_DEEPSLATE("Chiseled Deepslate", Dimension.OVERWORLD, 0),
	DEEPSLATE_COAL_ORE("Deepslate Coal Ore", Dimension.OVERWORLD, 0),
	DEEPSLATE_COPPER_ORE("Deepslate Copper Ore", Dimension.OVERWORLD, 0),
	DEEPSLATE_IRON_ORE("Deepslate Iron Ore", Dimension.OVERWORLD, 0),
	DEEPSLATE_GOLD_ORE("Deepslate Gold Ore", Dimension.OVERWORLD, 0),
	DEEPSLATE_REDSTONE_ORE("Deepslate Redstone Ore", Dimension.OVERWORLD, 0),
	DEEPSLATE_LAPIS_LAZULI_ORE("Deepslate Lapis Lazuli Ore", Dimension.OVERWORLD, 0),
	DEEPSLATE_DIAMOND_ORE("Deepslate Diamond Ore", Dimension.OVERWORLD, 0),
	DEEPSLATE_EMERALD_ORE("Deepslate Emerald Ore", Dimension.OVERWORLD, 0),
	COPPER_INGOT("Copper Ingot", Dimension.OVERWORLD, 0),
	RAW_COPPER_BLOCK("Block of Raw Copper", Dimension.OVERWORLD, 0),
	COPPER_BLOCK("Block of Copper", Dimension.OVERWORLD, 0),
	CUT_COPPER("Cut Copper", Dimension.OVERWORLD, 0),
	CUT_COPPER_SLAB("Cut Copper Slab", Dimension.OVERWORLD, 0),
	CUT_COPPER_STAIRS("Cut Copper Stairs", Dimension.OVERWORLD, 0),
	COPPER_GRATE("Copper Grate", Dimension.OVERWORLD, 0),
	COPPER_DOOR("Copper Door", Dimension.OVERWORLD, 0),
	COPPER_TRAPDOOR("Copper Trapdoor", Dimension.OVERWORLD, 0),
	COPPER_BULB("Copper Bulb", Dimension.OVERWORLD, 0),
	TINTED_GLASS("Tinted Glass", Dimension.OVERWORLD, 0),
	TUFF_BRICKS("Tuff Bricks", Dimension.OVERWORLD, 0),
	TUFF_BRICK_SLAB("Tuff Brick Slab", Dimension.OVERWORLD, 0),
	TUFF_BRICK_STAIRS("Tuff Brick Stairs", Dimension.OVERWORLD, 0),
	TUFF_BRICK_WALL("Tuff Brick Wall", Dimension.OVERWORLD, 0),
	CHISELED_TUFF_BRICKS("Chiseled Tuff Bricks", Dimension.OVERWORLD, 0),
	CHISELED_TUFF("Chiseled Tuff", Dimension.OVERWORLD, 0),
	POLISHED_TUFF("Polished Tuff", Dimension.OVERWORLD, 0),
	POLISHED_TUFF_SLAB("Polished Tuff Slab", Dimension.OVERWORLD, 0),
	POLISHED_TUFF_STAIRS("Polished Tuff Stairs", Dimension.OVERWORLD, 0),
	POLISHED_TUFF_WALL("Polished Tuff Wall", Dimension.OVERWORLD, 0),
	SPONGE("Sponge", Dimension.OVERWORLD, 0),
	WET_SPONGE("Wet Sponge", Dimension.OVERWORLD, 0),
	MOSS_BLOCK("Moss Block", Dimension.OVERWORLD, 0),
	MOSS_CARPET("Moss Carpet", Dimension.OVERWORLD, 0),
	BIG_DRIPLEAF("Big Dripleaf", Dimension.OVERWORLD, 0),
	SMALL_DRIPLEAF("Small Dripleaf", Dimension.OVERWORLD, 0),
	SPORE_BLOSSOM("Spore Blossom", Dimension.OVERWORLD, 0),
	BEE_NEST("Bee Nest", Dimension.OVERWORLD, 0),
	BEEHIVE("Beehive", Dimension.OVERWORLD, 0),
	HONEYCOMB("Honeycomb", Dimension.OVERWORLD, 0),
	HONEYCOMB_BLOCK("Honeycomb Block", Dimension.OVERWORLD, 0),
	OAK_SIGN("Oak Sign", Dimension.OVERWORLD, 0),
	SPRUCE_SIGN("Spruce Sign", Dimension.OVERWORLD, 0),
	BIRCH_SIGN("Birch Sign", Dimension.OVERWORLD, 0),
	JUNGLE_SIGN("Jungle Sign", Dimension.OVERWORLD, 0),
	ACACIA_SIGN("Acacia Sign", Dimension.OVERWORLD, 0),
	DARK_OAK_SIGN("Dark Oak Sign", Dimension.OVERWORLD, 0),
	MANGROVE_SIGN("Mangrove Sign", Dimension.OVERWORLD, 0),
	BAMBOO_SIGN("Bamboo Sign", Dimension.OVERWORLD, 0),
	CHERRY_SIGN("Cherry Sign", Dimension.OVERWORLD, 0),
	OAK_HANGING_SIGN("Oak Hanging Sign", Dimension.OVERWORLD, 0),
	SPRUCE_HANGING_SIGN("Spruce Hanging Sign", Dimension.OVERWORLD, 0),
	BIRCH_HANGING_SIGN("Birch Hanging Sign", Dimension.OVERWORLD, 0),
	JUNGLE_HANGING_SIGN("Jungle Hanging Sign", Dimension.OVERWORLD, 0),
	ACACIA_HANGING_SIGN("Acacia Hanging Sign", Dimension.OVERWORLD, 0),
	DARK_OAK_HANGING_SIGN("Dark Oak Hanging Sign", Dimension.OVERWORLD, 0),
	MANGROVE_HANGING_SIGN("Mangrove Hanging Sign", Dimension.OVERWORLD, 0),
	BAMBOO_HANGING_SIGN("Bamboo Hanging Sign", Dimension.OVERWORLD, 0),
	CHERRY_HANGING_SIGN("Cherry Hanging Sign", Dimension.OVERWORLD, 0),
	CHERRY_LOG("Cherry Log", Dimension.OVERWORLD, 0),
	CHERRY_PLANKS("Cherry Planks", Dimension.OVERWORLD, 0),
	CHERRY_SAPLING("Cherry Sapling", Dimension.OVERWORLD, 0),
	CHERRY_LEAVES("Cherry Leaves", Dimension.OVERWORLD, 0),
	CHERRY_BOAT("Cherry Boat", Dimension.OVERWORLD, 0),
	CHERRY_WOOD("Cherry Wood", Dimension.OVERWORLD, 0),
	CHERRY_FENCE("Cherry Fence", Dimension.OVERWORLD, 0),
	CHERRY_FENCE_GATE("Cherry Fence Gate", Dimension.OVERWORLD, 0),
	CHERRY_DOOR("Cherry Door", Dimension.OVERWORLD, 0),
	CHERRY_TRAPDOOR("Cherry Trapdoor", Dimension.OVERWORLD, 0),
	CHERRY_SLAB("Cherry Slab", Dimension.OVERWORLD, 0),
	CHERRY_STAIRS("Cherry Stairs", Dimension.OVERWORLD, 0),
	CHERRY_BUTTON("Cherry Button", Dimension.OVERWORLD, 0),
	CHERRY_PRESSURE_PLATE("Cherry Pressure Plate", Dimension.OVERWORLD, 0),
	STRIPPED_CHERRY_LOG("Stripped Cherry Log", Dimension.OVERWORLD, 0),
	STRIPPED_CHERRY_WOOD("Stripped Cherry Wood", Dimension.OVERWORLD, 0),
	PITCHER_POD("Pitcher Pod", Dimension.OVERWORLD, 0),
	TORCHFLOWER_SEEDS("Torchflower Seeds", Dimension.OVERWORLD, 0),
	SNIFFER_EGG("Sniffer Egg", Dimension.OVERWORLD, 0),
	TORCHFLOWER("Torchflower", Dimension.OVERWORLD, 0),
	PITCHER_PLANT("Pitcher Plant", Dimension.OVERWORLD, 0),
	BUSH("Bush", Dimension.OVERWORLD, 0),
	CACTUS_FLOWER("Cactus Flower", Dimension.OVERWORLD, 0),
	WILDFLOWERS("Wildflowers", Dimension.OVERWORLD, 0),
	LEAF_LITTER("Leaf Litter", Dimension.OVERWORLD, 0),
	PALE_HANGING_MOSS("Pale Hanging Moss", Dimension.OVERWORLD, 0),
	PALE_MOSS_BLOCK("Pale Moss Block", Dimension.OVERWORLD, 0),
	PALE_MOSS_CARPET("Pale Moss Carpet", Dimension.OVERWORLD, 0),
	SHORT_DRY_GRASS("Short Dry Grass", Dimension.OVERWORLD, 0),
	TALL_DRY_GRASS("Tall Dry Grass", Dimension.OVERWORLD, 0),
	OPEN_EYEBLOSSOM("Open Eyeblossom", Dimension.OVERWORLD, 0),
	CLOSED_EYEBLOSSOM("Closed Eyeblossom", Dimension.OVERWORLD, 0),
	FIREFLY_BUSH("Firefly Bush", Dimension.OVERWORLD, 0),

	IRON_INGOT("Iron Ingot", Dimension.OVERWORLD, 1),
	GOLD_INGOT("Gold Ingot", Dimension.OVERWORLD, 1),
	REDSTONE_BLOCK("Block of Redstone", Dimension.OVERWORLD, 1),
	IRON_BLOCK("Block of Iron", Dimension.OVERWORLD, 1),
	GOLD_BLOCK("Block of Gold", Dimension.OVERWORLD, 1),
	DIAMOND_BLOCK("Block of Diamond", Dimension.OVERWORLD, 1),
	EMERALD_BLOCK("Block of Emerald", Dimension.OVERWORLD, 1),
	LAPIS_LAZULI_BLOCK("Block of Lapis Lazuli", Dimension.OVERWORLD, 1),
	COAL_BLOCK("Block of Coal", Dimension.OVERWORLD, 1),
	RAW_IRON_BLOCK("Block of Raw Iron", Dimension.OVERWORLD, 1),
	RAW_GOLD_BLOCK("Block of Raw Gold", Dimension.OVERWORLD, 1),
	STONE_BUTTON("Stone Button", Dimension.OVERWORLD, 1),
	STONE_PRESSURE_PLATE("Stone Pressure Plate", Dimension.OVERWORLD, 1),
	LEVER("Lever", Dimension.OVERWORLD, 1),
	TORCH("Torch", Dimension.OVERWORLD, 1),
	LADDER("Ladder", Dimension.OVERWORLD, 1),
	IRON_BARS("Iron Bars", Dimension.OVERWORLD, 1),
	GLASS_BOTTLE("Glass Bottle", Dimension.OVERWORLD, 1),
	BONE_BLOCK("Bone Block", Dimension.OVERWORLD, 1),
	GOLD_NUGGET("Gold Nugget", Dimension.OVERWORLD, 1),
	IRON_NUGGET("Iron Nugget", Dimension.OVERWORLD, 1),
	COOKED_COD("Cooked Cod", Dimension.OVERWORLD, 1),
	COOKED_SALMON("Cooked Salmon", Dimension.OVERWORLD, 1),
	BAKED_POTATO("Baked Potato", Dimension.OVERWORLD, 1),
	APPLE_GOLDEN("Golden Apple", Dimension.OVERWORLD, 1),
	PUMPKIN_PIE("Pumpkin Pie", Dimension.OVERWORLD, 1),
	COOKED_CHICKEN("Cooked Chicken", Dimension.OVERWORLD, 1),
	COOKED_PORKCHOP("Cooked Porkchop", Dimension.OVERWORLD, 1),
	STEAK("Steak", Dimension.OVERWORLD, 1),
	COOKED_MUTTON("Cooked Mutton", Dimension.OVERWORLD, 1),
	COOKED_RABBIT("Cooked Rabbit", Dimension.OVERWORLD, 1),
	MUSHROOM_STEW("Mushroom Stew", Dimension.OVERWORLD, 1),
	BEETROOT_SOUP("Beetroot Soup", Dimension.OVERWORLD, 1),
	SUSPICIOUS_STEW("Suspicious Stew", Dimension.OVERWORLD, 1),
	HAY_BALE("Hay Bale", Dimension.OVERWORLD, 1),
	BAMBOO("Bamboo", Dimension.OVERWORLD, 1),
	BLACK_DYE("Black Dye", Dimension.OVERWORLD, 1),
	RED_DYE("Red Dye", Dimension.OVERWORLD, 1),
	GREEN_DYE("Green Dye", Dimension.OVERWORLD, 1),
	BROWN_DYE("Brown Dye", Dimension.OVERWORLD, 1),
	BLUE_DYE("Blue Dye", Dimension.OVERWORLD, 1),
	PURPLE_DYE("Purple Dye", Dimension.OVERWORLD, 1),
	CYAN_DYE("Cyan Dye", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_DYE("Light Gray Dye", Dimension.OVERWORLD, 1),
	GRAY_DYE("Gray Dye", Dimension.OVERWORLD, 1),
	PINK_DYE("Pink Dye", Dimension.OVERWORLD, 1),
	LIME_DYE("Lime Dye", Dimension.OVERWORLD, 1),
	YELLOW_DYE("Yellow Dye", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_DYE("Light Blue Dye", Dimension.OVERWORLD, 1),
	MAGENTA_DYE("Magenta Dye", Dimension.OVERWORLD, 1),
	ORANGE_DYE("Orange Dye", Dimension.OVERWORLD, 1),
	WHITE_DYE("White Dye", Dimension.OVERWORLD, 1),
	INK_SAC("Ink Sac", Dimension.OVERWORLD, 1),
	COCOA_BEANS_ITEM("Cocoa Beans", Dimension.OVERWORLD, 1), // As item form
	HONEY_BOTTLE("Honey Bottle", Dimension.OVERWORLD, 1),
	LEATHER("Leather", Dimension.OVERWORLD, 1),
	RABBIT_HIDE("Rabbit Hide", Dimension.OVERWORLD, 1),
	SPONGE_WET("Wet Sponge", Dimension.OVERWORLD, 1),
	MINECART("Minecart", Dimension.OVERWORLD, 1),
	RAIL("Rail", Dimension.OVERWORLD, 1),
	POWERED_RAIL("Powered Rail", Dimension.OVERWORLD, 1),
	DETECTOR_RAIL("Detector Rail", Dimension.OVERWORLD, 1),
	ACTIVATOR_RAIL("Activator Rail", Dimension.OVERWORLD, 1),
	IRON_DOOR("Iron Door", Dimension.OVERWORLD, 1),
	IRON_TRAPDOOR("Iron Trapdoor", Dimension.OVERWORLD, 1),
	FLINT_AND_STEEL("Flint and Steel", Dimension.OVERWORLD, 1),
	FISHING_ROD("Fishing Rod", Dimension.OVERWORLD, 1),
	SHEARS("Shears", Dimension.OVERWORLD, 1),
	BUCKET("Bucket", Dimension.OVERWORLD, 1),
	WATER_BUCKET("Water Bucket", Dimension.OVERWORLD, 1),
	MILK_BUCKET("Milk Bucket", Dimension.OVERWORLD, 1),
	POWDER_SNOW_BUCKET("Powder Snow Bucket", Dimension.OVERWORLD, 1),
	IRON_SHOVEL("Iron Shovel", Dimension.OVERWORLD, 1),
	IRON_PICKAXE("Iron Pickaxe", Dimension.OVERWORLD, 1),
	IRON_AXE("Iron Axe", Dimension.OVERWORLD, 1),
	IRON_HOE("Iron Hoe", Dimension.OVERWORLD, 1),
	IRON_SWORD("Iron Sword", Dimension.OVERWORLD, 1),
	GOLDEN_SHOVEL("Golden Shovel", Dimension.OVERWORLD, 1),
	GOLDEN_PICKAXE("Golden Pickaxe", Dimension.OVERWORLD, 1),
	GOLDEN_AXE("Golden Axe", Dimension.OVERWORLD, 1),
	GOLDEN_HOE("Golden Hoe", Dimension.OVERWORLD, 1),
	GOLDEN_SWORD("Golden Sword", Dimension.OVERWORLD, 1),
	STONE_SHOVEL("Stone Shovel", Dimension.OVERWORLD, 1),
	STONE_PICKAXE("Stone Pickaxe", Dimension.OVERWORLD, 1),
	STONE_AXE("Stone Axe", Dimension.OVERWORLD, 1),
	STONE_HOE("Stone Hoe", Dimension.OVERWORLD, 1),
	STONE_SWORD("Stone Sword", Dimension.OVERWORLD, 1),
	WOODEN_SHOVEL("Wooden Shovel", Dimension.OVERWORLD, 1),
	WOODEN_PICKAXE("Wooden Pickaxe", Dimension.OVERWORLD, 1),
	WOODEN_AXE("Wooden Axe", Dimension.OVERWORLD, 1),
	WOODEN_HOE("Wooden Hoe", Dimension.OVERWORLD, 1),
	WOODEN_SWORD("Wooden Sword", Dimension.OVERWORLD, 1),
	LEATHER_CAP("Leather Cap", Dimension.OVERWORLD, 1),
	LEATHER_TUNIC("Leather Tunic", Dimension.OVERWORLD, 1),
	LEATHER_PANTS("Leather Pants", Dimension.OVERWORLD, 1),
	LEATHER_BOOTS("Leather Boots", Dimension.OVERWORLD, 1),
	GOLDEN_HELMET("Golden Helmet", Dimension.OVERWORLD, 1),
	GOLDEN_CHESTPLATE("Golden Chestplate", Dimension.OVERWORLD, 1),
	GOLDEN_LEGGINGS("Golden Leggings", Dimension.OVERWORLD, 1),
	GOLDEN_BOOTS("Golden Boots", Dimension.OVERWORLD, 1),
	IRON_HELMET("Iron Helmet", Dimension.OVERWORLD, 1),
	IRON_CHESTPLATE("Iron Chestplate", Dimension.OVERWORLD, 1),
	IRON_LEGGINGS("Iron Leggings", Dimension.OVERWORLD, 1),
	IRON_BOOTS("Iron Boots", Dimension.OVERWORLD, 1),
	BLACK_BANNER("Black Banner", Dimension.OVERWORLD, 1),
	BLUE_BANNER("Blue Banner", Dimension.OVERWORLD, 1),
	BROWN_BANNER("Brown Banner", Dimension.OVERWORLD, 1),
	CYAN_BANNER("Cyan Banner", Dimension.OVERWORLD, 1),
	GRAY_BANNER("Gray Banner", Dimension.OVERWORLD, 1),
	GREEN_BANNER("Green Banner", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_BANNER("Light Blue Banner", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_BANNER("Light Gray Banner", Dimension.OVERWORLD, 1),
	LIME_BANNER("Lime Banner", Dimension.OVERWORLD, 1),
	MAGENTA_BANNER("Magenta Banner", Dimension.OVERWORLD, 1),
	ORANGE_BANNER("Orange Banner", Dimension.OVERWORLD, 1),
	PINK_BANNER("Pink Banner", Dimension.OVERWORLD, 1),
	PURPLE_BANNER("Purple Banner", Dimension.OVERWORLD, 1),
	RED_BANNER("Red Banner", Dimension.OVERWORLD, 1),
	WHITE_BANNER("White Banner", Dimension.OVERWORLD, 1),
	YELLOW_BANNER("Yellow Banner", Dimension.OVERWORLD, 1),
	BLACK_BED("Black Bed", Dimension.OVERWORLD, 1),
	BLUE_BED("Blue Bed", Dimension.OVERWORLD, 1),
	BROWN_BED("Brown Bed", Dimension.OVERWORLD, 1),
	CYAN_BED("Cyan Bed", Dimension.OVERWORLD, 1),
	GRAY_BED("Gray Bed", Dimension.OVERWORLD, 1),
	GREEN_BED("Green Bed", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_BED("Light Blue Bed", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_BED("Light Gray Bed", Dimension.OVERWORLD, 1),
	LIME_BED("Lime Bed", Dimension.OVERWORLD, 1),
	MAGENTA_BED("Magenta Bed", Dimension.OVERWORLD, 1),
	ORANGE_BED("Orange Bed", Dimension.OVERWORLD, 1),
	PINK_BED("Pink Bed", Dimension.OVERWORLD, 1),
	PURPLE_BED("Purple Bed", Dimension.OVERWORLD, 1),
	RED_BED("Red Bed", Dimension.OVERWORLD, 1),
	WHITE_BED("White Bed", Dimension.OVERWORLD, 1),
	YELLOW_BED("Yellow Bed", Dimension.OVERWORLD, 1),
	BLACK_CANDLE("Black Candle", Dimension.OVERWORLD, 1),
	BLUE_CANDLE("Blue Candle", Dimension.OVERWORLD, 1),
	BROWN_CANDLE("Brown Candle", Dimension.OVERWORLD, 1),
	CYAN_CANDLE("Cyan Candle", Dimension.OVERWORLD, 1),
	GRAY_CANDLE("Gray Candle", Dimension.OVERWORLD, 1),
	GREEN_CANDLE("Green Candle", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_CANDLE("Light Blue Candle", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_CANDLE("Light Gray Candle", Dimension.OVERWORLD, 1),
	LIME_CANDLE("Lime Candle", Dimension.OVERWORLD, 1),
	MAGENTA_CANDLE("Magenta Candle", Dimension.OVERWORLD, 1),
	ORANGE_CANDLE("Orange Candle", Dimension.OVERWORLD, 1),
	PINK_CANDLE("Pink Candle", Dimension.OVERWORLD, 1),
	PURPLE_CANDLE("Purple Candle", Dimension.OVERWORLD, 1),
	RED_CANDLE("Red Candle", Dimension.OVERWORLD, 1),
	WHITE_CANDLE("White Candle", Dimension.OVERWORLD, 1),
	YELLOW_CANDLE("Yellow Candle", Dimension.OVERWORLD, 1),
	CANDLE("Candle", Dimension.OVERWORLD, 1),
	BLACK_CARPET("Black Carpet", Dimension.OVERWORLD, 1),
	BLUE_CARPET("Blue Carpet", Dimension.OVERWORLD, 1),
	BROWN_CARPET("Brown Carpet", Dimension.OVERWORLD, 1),
	CYAN_CARPET("Cyan Carpet", Dimension.OVERWORLD, 1),
	GRAY_CARPET("Gray Carpet", Dimension.OVERWORLD, 1),
	GREEN_CARPET("Green Carpet", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_CARPET("Light Blue Carpet", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_CARPET("Light Gray Carpet", Dimension.OVERWORLD, 1),
	LIME_CARPET("Lime Carpet", Dimension.OVERWORLD, 1),
	MAGENTA_CARPET("Magenta Carpet", Dimension.OVERWORLD, 1),
	ORANGE_CARPET("Orange Carpet", Dimension.OVERWORLD, 1),
	PINK_CARPET("Pink Carpet", Dimension.OVERWORLD, 1),
	PURPLE_CARPET("Purple Carpet", Dimension.OVERWORLD, 1),
	RED_CARPET("Red Carpet", Dimension.OVERWORLD, 1),
	WHITE_CARPET("White Carpet", Dimension.OVERWORLD, 1),
	YELLOW_CARPET("Yellow Carpet", Dimension.OVERWORLD, 1),
	BLACK_CONCRETE("Black Concrete", Dimension.OVERWORLD, 1),
	BLUE_CONCRETE("Blue Concrete", Dimension.OVERWORLD, 1),
	BROWN_CONCRETE("Brown Concrete", Dimension.OVERWORLD, 1),
	CYAN_CONCRETE("Cyan Concrete", Dimension.OVERWORLD, 1),
	GRAY_CONCRETE("Gray Concrete", Dimension.OVERWORLD, 1),
	GREEN_CONCRETE("Green Concrete", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_CONCRETE("Light Blue Concrete", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_CONCRETE("Light Gray Concrete", Dimension.OVERWORLD, 1),
	LIME_CONCRETE("Lime Concrete", Dimension.OVERWORLD, 1),
	MAGENTA_CONCRETE("Magenta Concrete", Dimension.OVERWORLD, 1),
	ORANGE_CONCRETE("Orange Concrete", Dimension.OVERWORLD, 1),
	PINK_CONCRETE("Pink Concrete", Dimension.OVERWORLD, 1),
	PURPLE_CONCRETE("Purple Concrete", Dimension.OVERWORLD, 1),
	RED_CONCRETE("Red Concrete", Dimension.OVERWORLD, 1),
	WHITE_CONCRETE("White Concrete", Dimension.OVERWORLD, 1),
	YELLOW_CONCRETE("Yellow Concrete", Dimension.OVERWORLD, 1),
	BLACK_CONCRETE_POWDER("Black Concrete Powder", Dimension.OVERWORLD, 1),
	BLUE_CONCRETE_POWDER("Blue Concrete Powder", Dimension.OVERWORLD, 1),
	BROWN_CONCRETE_POWDER("Brown Concrete Powder", Dimension.OVERWORLD, 1),
	CYAN_CONCRETE_POWDER("Cyan Concrete Powder", Dimension.OVERWORLD, 1),
	GRAY_CONCRETE_POWDER("Gray Concrete Powder", Dimension.OVERWORLD, 1),
	GREEN_CONCRETE_POWDER("Green Concrete Powder", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_CONCRETE_POWDER("Light Blue Concrete Powder", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_CONCRETE_POWDER("Light Gray Concrete Powder", Dimension.OVERWORLD, 1),
	LIME_CONCRETE_POWDER("Lime Concrete Powder", Dimension.OVERWORLD, 1),
	MAGENTA_CONCRETE_POWDER("Magenta Concrete Powder", Dimension.OVERWORLD, 1),
	ORANGE_CONCRETE_POWDER("Orange Concrete Powder", Dimension.OVERWORLD, 1),
	PINK_CONCRETE_POWDER("Pink Concrete Powder", Dimension.OVERWORLD, 1),
	PURPLE_CONCRETE_POWDER("Purple Concrete Powder", Dimension.OVERWORLD, 1),
	RED_CONCRETE_POWDER("Red Concrete Powder", Dimension.OVERWORLD, 1),
	WHITE_CONCRETE_POWDER("White Concrete Powder", Dimension.OVERWORLD, 1),
	YELLOW_CONCRETE_POWDER("Yellow Concrete Powder", Dimension.OVERWORLD, 1),
	BLACK_TERRACOTTA("Black Terracotta", Dimension.OVERWORLD, 1),
	BLUE_TERRACOTTA("Blue Terracotta", Dimension.OVERWORLD, 1),
	BROWN_TERRACOTTA("Brown Terracotta", Dimension.OVERWORLD, 1),
	CYAN_TERRACOTTA("Cyan Terracotta", Dimension.OVERWORLD, 1),
	GRAY_TERRACOTTA("Gray Terracotta", Dimension.OVERWORLD, 1),
	GREEN_TERRACOTTA("Green Terracotta", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_TERRACOTTA("Light Blue Terracotta", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_TERRACOTTA("Light Gray Terracotta", Dimension.OVERWORLD, 1),
	LIME_TERRACOTTA("Lime Terracotta", Dimension.OVERWORLD, 1),
	MAGENTA_TERRACOTTA("Magenta Terracotta", Dimension.OVERWORLD, 1),
	ORANGE_TERRACOTTA("Orange Terracotta", Dimension.OVERWORLD, 1),
	PINK_TERRACOTTA("Pink Terracotta", Dimension.OVERWORLD, 1),
	PURPLE_TERRACOTTA("Purple Terracotta", Dimension.OVERWORLD, 1),
	RED_TERRACOTTA("Red Terracotta", Dimension.OVERWORLD, 1),
	WHITE_TERRACOTTA("White Terracotta", Dimension.OVERWORLD, 1),
	YELLOW_TERRACOTTA("Yellow Terracotta", Dimension.OVERWORLD, 1),
	BLACK_GLAZED_TERRACOTTA("Black Glazed Terracotta", Dimension.OVERWORLD, 1),
	BLUE_GLAZED_TERRACOTTA("Blue Glazed Terracotta", Dimension.OVERWORLD, 1),
	BROWN_GLAZED_TERRACOTTA("Brown Glazed Terracotta", Dimension.OVERWORLD, 1),
	CYAN_GLAZED_TERRACOTTA("Cyan Glazed Terracotta", Dimension.OVERWORLD, 1),
	GRAY_GLAZED_TERRACOTTA("Gray Glazed Terracotta", Dimension.OVERWORLD, 1),
	GREEN_GLAZED_TERRACOTTA("Green Glazed Terracotta", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_GLAZED_TERRACOTTA("Light Blue Glazed Terracotta", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_GLAZED_TERRACOTTA("Light Gray Glazed Terracotta", Dimension.OVERWORLD, 1),
	LIME_GLAZED_TERRACOTTA("Lime Glazed Terracotta", Dimension.OVERWORLD, 1),
	MAGENTA_GLAZED_TERRACOTTA("Magenta Glazed Terracotta", Dimension.OVERWORLD, 1),
	ORANGE_GLAZED_TERRACOTTA("Orange Glazed Terracotta", Dimension.OVERWORLD, 1),
	PINK_GLAZED_TERRACOTTA("Pink Glazed Terracotta", Dimension.OVERWORLD, 1),
	PURPLE_GLAZED_TERRACOTTA("Purple Glazed Terracotta", Dimension.OVERWORLD, 1),
	RED_GLAZED_TERRACOTTA("Red Glazed Terracotta", Dimension.OVERWORLD, 1),
	WHITE_GLAZED_TERRACOTTA("White Glazed Terracotta", Dimension.OVERWORLD, 1),
	YELLOW_GLAZED_TERRACOTTA("Yellow Glazed Terracotta", Dimension.OVERWORLD, 1),
	WHITE_WOOL("White Wool", Dimension.OVERWORLD, 1),
	ORANGE_WOOL("Orange Wool", Dimension.OVERWORLD, 1),
	MAGENTA_WOOL("Magenta Wool", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_WOOL("Light Blue Wool", Dimension.OVERWORLD, 1),
	YELLOW_WOOL("Yellow Wool", Dimension.OVERWORLD, 1),
	LIME_WOOL("Lime Wool", Dimension.OVERWORLD, 1),
	PINK_WOOL("Pink Wool", Dimension.OVERWORLD, 1),
	GRAY_WOOL("Gray Wool", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_WOOL("Light Gray Wool", Dimension.OVERWORLD, 1),
	CYAN_WOOL("Cyan Wool", Dimension.OVERWORLD, 1),
	PURPLE_WOOL("Purple Wool", Dimension.OVERWORLD, 1),
	BLUE_WOOL("Blue Wool", Dimension.OVERWORLD, 1),
	BROWN_WOOL("Brown Wool", Dimension.OVERWORLD, 1),
	GREEN_WOOL("Green Wool", Dimension.OVERWORLD, 1),
	RED_WOOL("Red Wool", Dimension.OVERWORLD, 1),
	BLACK_WOOL("Black Wool", Dimension.OVERWORLD, 1),
	CHEST("Chest", Dimension.OVERWORLD, 1),
	TRAPPED_CHEST("Trapped Chest", Dimension.OVERWORLD, 1),
	CRAFTING_TABLE("Crafting Table", Dimension.OVERWORLD, 1),
	FURNACE("Furnace", Dimension.OVERWORLD, 1),
	CAULDRON("Cauldron", Dimension.OVERWORLD, 1),
	COMPOSTER("Composter", Dimension.OVERWORLD, 1),
	FLOWER_POT("Flower Pot", Dimension.OVERWORLD, 1),
	BELL("Bell", Dimension.OVERWORLD, 1),
	JUKEBOX("Jukebox", Dimension.OVERWORLD, 1),
	NOTE_BLOCK("Note Block", Dimension.OVERWORLD, 1),
	OBSERVER("Observer", Dimension.OVERWORLD, 1),
	DAYLIGHT_DETECTOR("Daylight Detector", Dimension.OVERWORLD, 1),
	DISPENSER("Dispenser", Dimension.OVERWORLD, 1),
	DROPPER("Dropper", Dimension.OVERWORLD, 1),
	HOPPER("Hopper", Dimension.OVERWORLD, 1),
	PISTON("Piston", Dimension.OVERWORLD, 1),
	STICKY_PISTON("Sticky Piston", Dimension.OVERWORLD, 1),
	REDSTONE_TORCH("Redstone Torch", Dimension.OVERWORLD, 1),
	REDSTONE_REPEATER("Redstone Repeater", Dimension.OVERWORLD, 1),
	REDSTONE_COMPARATOR("Redstone Comparator", Dimension.OVERWORLD, 1),
	REDSTONE_LAMP("Redstone Lamp", Dimension.OVERWORLD, 1),
	TARGET("Target", Dimension.OVERWORLD, 1),
	LIGHT_WEIGHTED_PRESSURE_PLATE("Light Weighted Pressure Plate", Dimension.OVERWORLD, 1),
	HEAVY_WEIGHTED_PRESSURE_PLATE("Heavy Weighted Pressure Plate", Dimension.OVERWORLD, 1),
	LEATHER_HORSE_ARMOR("Leather Horse Armor", Dimension.OVERWORLD, 1),
	GOLDEN_HORSE_ARMOR("Golden Horse Armor", Dimension.OVERWORLD, 1),
	IRON_HORSE_ARMOR("Iron Horse Armor", Dimension.OVERWORLD, 1),
	COBWEB("Cobweb", Dimension.OVERWORLD, 1),
	ENCHANTING_TABLE("Enchanting Table", Dimension.OVERWORLD, 1),
	BREWING_STAND("Brewing Stand", Dimension.OVERWORLD, 1),
	BOOK("Book", Dimension.OVERWORLD, 1),
	BOOKSHELF("Bookshelf", Dimension.OVERWORLD, 1),
	LECTERN("Lectern", Dimension.OVERWORLD, 1),
	ITEM_FRAME("Item Frame", Dimension.OVERWORLD, 1),
	GLOW_ITEM_FRAME("Glow Item Frame", Dimension.OVERWORLD, 1),
	PAINTING("Painting", Dimension.OVERWORLD, 1),
	ARMOR_STAND("Armor Stand", Dimension.OVERWORLD, 1),
	SCROLL("Scroll", Dimension.OVERWORLD, 1), // Assuming this is an in-game item
	FLETCHING_TABLE("Fletching Table", Dimension.OVERWORLD, 1),
	CARTOGRAPHY_TABLE("Cartography Table", Dimension.OVERWORLD, 1),
	GRINDSTONE("Grindstone", Dimension.OVERWORLD, 1),
	SMITHING_TABLE("Smithing Table", Dimension.OVERWORLD, 1),
	LOOM("Loom", Dimension.OVERWORLD, 1),
	STONECUTTER("Stonecutter", Dimension.OVERWORLD, 1),
	SMOKER("Smoker", Dimension.OVERWORLD, 1),
	BLAST_FURNACE("Blast Furnace", Dimension.OVERWORLD, 1),
	BARREL("Barrel", Dimension.OVERWORLD, 1),
	LANTERN("Lantern", Dimension.OVERWORLD, 1),
	SOUL_LANTERN("Soul Lantern", Dimension.OVERWORLD, 1),
	CAMPFIRE("Campfire", Dimension.OVERWORLD, 1),
	SOUL_CAMPFIRE("Soul Campfire", Dimension.OVERWORLD, 1),
	LIGHTNING_ROD("Lightning Rod", Dimension.OVERWORLD, 1),
	CARROT_ON_A_STICK("Carrot on a Stick", Dimension.OVERWORLD, 1),
	FISHING_ROD_ENCHANTED("Fishing Rod", Dimension.OVERWORLD, 1), // If enchanted. If only generic fishing rod, then difficulty 1.
	LEAD("Lead", Dimension.OVERWORLD, 1),
	WHITE_STAINED_GLASS("White Stained Glass", Dimension.OVERWORLD, 1),
	ORANGE_STAINED_GLASS("Orange Stained Glass", Dimension.OVERWORLD, 1),
	MAGENTA_STAINED_GLASS("Magenta Stained Glass", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_STAINED_GLASS("Light Blue Stained Glass", Dimension.OVERWORLD, 1),
	YELLOW_STAINED_GLASS("Yellow Stained Glass", Dimension.OVERWORLD, 1),
	LIME_STAINED_GLASS("Lime Stained Glass", Dimension.OVERWORLD, 1),
	PINK_STAINED_GLASS("Pink Stained Glass", Dimension.OVERWORLD, 1),
	GRAY_STAINED_GLASS("Gray Stained Glass", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_STAINED_GLASS("Light Gray Stained Glass", Dimension.OVERWORLD, 1),
	CYAN_STAINED_GLASS("Cyan Stained Glass", Dimension.OVERWORLD, 1),
	PURPLE_STAINED_GLASS("Purple Stained Glass", Dimension.OVERWORLD, 1),
	BLUE_STAINED_GLASS("Blue Stained Glass", Dimension.OVERWORLD, 1),
	BROWN_STAINED_GLASS("Brown Stained Glass", Dimension.OVERWORLD, 1),
	GREEN_STAINED_GLASS("Green Stained Glass", Dimension.OVERWORLD, 1),
	RED_STAINED_GLASS("Red Stained Glass", Dimension.OVERWORLD, 1),
	BLACK_STAINED_GLASS("Black Stained Glass", Dimension.OVERWORLD, 1),
	WHITE_STAINED_GLASS_PANE("White Stained Glass Pane", Dimension.OVERWORLD, 1),
	ORANGE_STAINED_GLASS_PANE("Orange Stained Glass Pane", Dimension.OVERWORLD, 1),
	MAGENTA_STAINED_GLASS_PANE("Magenta Stained Glass Pane", Dimension.OVERWORLD, 1),
	LIGHT_BLUE_STAINED_GLASS_PANE("Light Blue Stained Glass Pane", Dimension.OVERWORLD, 1),
	YELLOW_STAINED_GLASS_PANE("Yellow Stained Glass Pane", Dimension.OVERWORLD, 1),
	LIME_STAINED_GLASS_PANE("Lime Stained Glass Pane", Dimension.OVERWORLD, 1),
	PINK_STAINED_GLASS_PANE("Pink Stained Glass Pane", Dimension.OVERWORLD, 1),
	GRAY_STAINED_GLASS_PANE("Gray Stained Glass Pane", Dimension.OVERWORLD, 1),
	LIGHT_GRAY_STAINED_GLASS_PANE("Light Gray Stained Glass Pane", Dimension.OVERWORLD, 1),
	CYAN_STAINED_GLASS_PANE("Cyan Stained Glass Pane", Dimension.OVERWORLD, 1),
	PURPLE_STAINED_GLASS_PANE("Purple Stained Glass Pane", Dimension.OVERWORLD, 1),
	BLUE_STAINED_GLASS_PANE("Blue Stained Glass Pane", Dimension.OVERWORLD, 1),
	BROWN_STAINED_GLASS_PANE("Brown Stained Glass Pane", Dimension.OVERWORLD, 1),
	GREEN_STAINED_GLASS_PANE("Green Stained Glass Pane", Dimension.OVERWORLD, 1),
	RED_STAINED_GLASS_PANE("Red Stained Glass Pane", Dimension.OVERWORLD, 1),
	BLACK_STAINED_GLASS_PANE("Black Stained Glass Pane", Dimension.OVERWORLD, 1),
	CHISELED_BOOKSHELF("Chiseled Bookshelf", Dimension.OVERWORLD, 1),
	EXPOSED_COPPER("Exposed Copper", Dimension.OVERWORLD, 1),
	EXPOSED_CUT_COPPER("Exposed Cut Copper", Dimension.OVERWORLD, 1),
	EXPOSED_CUT_COPPER_SLAB("Exposed Cut Copper Slab", Dimension.OVERWORLD, 1),
	EXPOSED_CUT_COPPER_STAIRS("Exposed Cut Copper Stairs", Dimension.OVERWORLD, 1),
	EXPOSED_COPPER_GRATE("Exposed Copper Grate", Dimension.OVERWORLD, 1),
	EXPOSED_COPPER_DOOR("Exposed Copper Door", Dimension.OVERWORLD, 1),
	EXPOSED_COPPER_TRAPDOOR("Exposed Copper Trapdoor", Dimension.OVERWORLD, 1),
	EXPOSED_COPPER_BULB("Exposed Copper Bulb", Dimension.OVERWORLD, 1),
	WEATHERED_COPPER("Weathered Copper", Dimension.OVERWORLD, 1),
	WEATHERED_CUT_COPPER("Weathered Cut Copper", Dimension.OVERWORLD, 1),
	WEATHERED_CUT_COPPER_SLAB("Weathered Cut Copper Slab", Dimension.OVERWORLD, 1),
	WEATHERED_CUT_COPPER_STAIRS("Weathered Cut Copper Stairs", Dimension.OVERWORLD, 1),
	WEATHERED_COPPER_GRATE("Weathered Copper Grate", Dimension.OVERWORLD, 1),
	WEATHERED_COPPER_DOOR("Weathered Copper Door", Dimension.OVERWORLD, 1),
	WEATHERED_COPPER_TRAPDOOR("Weathered Copper Trapdoor", Dimension.OVERWORLD, 1),
	WEATHERED_COPPER_BULB("Weathered Copper Bulb", Dimension.OVERWORLD, 1),
	OXIDIZED_COPPER("Oxidized Copper", Dimension.OVERWORLD, 1),
	OXIDIZED_CUT_COPPER("Oxidized Cut Copper", Dimension.OVERWORLD, 1),
	OXIDIZED_CUT_COPPER_SLAB("Oxidized Cut Copper Slab", Dimension.OVERWORLD, 1),
	OXIDIZED_CUT_COPPER_STAIRS("Oxidized Cut Copper Stairs", Dimension.OVERWORLD, 1),
	OXIDIZED_COPPER_GRATE("Oxidized Copper Grate", Dimension.OVERWORLD, 1),
	OXIDIZED_COPPER_DOOR("Oxidized Copper Door", Dimension.OVERWORLD, 1),
	OXIDIZED_COPPER_TRAPDOOR("Oxidized Copper Trapdoor", Dimension.OVERWORLD, 1),
	OXIDIZED_COPPER_BULB("Oxidized Copper Bulb", Dimension.OVERWORLD, 1),
	CHISELED_COPPER("Chiseled Copper", Dimension.OVERWORLD, 1),
	EXPOSED_CHISELED_COPPER("Exposed Chiseled Copper", Dimension.OVERWORLD, 1),
	WEATHERED_CHISELED_COPPER("Weathered Chiseled Copper", Dimension.OVERWORLD, 1),
	OXIDIZED_CHISELED_COPPER("Oxidized Chiseled Copper", Dimension.OVERWORLD, 1),
	PINK_PETALS("Pink Petals", Dimension.OVERWORLD, 1),
	BRICK_DECORATED_POT("Brick Decorated Pot", Dimension.OVERWORLD, 1), // Crafted
	CRAFTER("Crafter", Dimension.OVERWORLD, 1),

	OAK_BOAT_WITH_CHEST("Oak Boat with Chest", Dimension.OVERWORLD, 2),
	SPRUCE_BOAT_WITH_CHEST("Spruce Boat with Chest", Dimension.OVERWORLD, 2),
	BIRCH_BOAT_WITH_CHEST("Birch Boat with Chest", Dimension.OVERWORLD, 2),
	JUNGLE_BOAT_WITH_CHEST("Jungle Boat with Chest", Dimension.OVERWORLD, 2),
	ACACIA_BOAT_WITH_CHEST("Acacia Boat with Chest", Dimension.OVERWORLD, 2),
	DARK_OAK_BOAT_WITH_CHEST("Dark Oak Boat with Chest", Dimension.OVERWORLD, 2),
	MANGROVE_BOAT_WITH_CHEST("Mangrove Boat with Chest", Dimension.OVERWORLD, 2),
	BAMBOO_RAFT_WITH_CHEST("Bamboo Raft with Chest", Dimension.OVERWORLD, 2),
	CHERRY_BOAT_WITH_CHEST("Cherry Boat with Chest", Dimension.OVERWORLD, 2),
	MINECART_WITH_CHEST("Minecart with Chest", Dimension.OVERWORLD, 2),
	MINECART_WITH_HOPPER("Minecart with Hopper", Dimension.OVERWORLD, 2),
	MINECART_WITH_TNT("Minecart with TNT", Dimension.OVERWORLD, 2),
	GOLDEN_CARROT("Golden Carrot", Dimension.OVERWORLD, 2),
	GLISTERING_MELON_SLICE("Glistering Melon Slice", Dimension.OVERWORLD, 2),
	DIAMOND_SHOVEL("Diamond Shovel", Dimension.OVERWORLD, 2),
	DIAMOND_PICKAXE("Diamond Pickaxe", Dimension.OVERWORLD, 2),
	DIAMOND_AXE("Diamond Axe", Dimension.OVERWORLD, 2),
	DIAMOND_HOE("Diamond Hoe", Dimension.OVERWORLD, 2),
	DIAMOND_SWORD("Diamond Sword", Dimension.OVERWORLD, 2),
	DIAMOND_HELMET("Diamond Helmet", Dimension.OVERWORLD, 2),
	DIAMOND_CHESTPLATE("Diamond Chestplate", Dimension.OVERWORLD, 2),
	DIAMOND_LEGGINGS("Diamond Leggings", Dimension.OVERWORLD, 2),
	DIAMOND_BOOTS("Diamond Boots", Dimension.OVERWORLD, 2),
	DIAMOND_HORSE_ARMOR("Diamond Horse Armor", Dimension.OVERWORLD, 2),
	CLOCK("Clock", Dimension.OVERWORLD, 2),
	COMPASS("Compass", Dimension.OVERWORLD, 2),
	ENCHANTED_GOLDEN_APPLE("Enchanted Golden Apple", Dimension.OVERWORLD, 2),
	TOTEM_OF_UNDYING("Totem of Undying", Dimension.OVERWORLD, 2),
	BOTTLE_O_ENCHANTING("Bottle o' Enchanting", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET("Firework Rocket", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_WHITE("Firework Star White", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_ORANGE("Firework Star Orange", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_MAGENTA("Firework Star Magenta", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_LIGHT_BLUE("Firework Star Light Blue", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_YELLOW("Firework Star Yellow", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_LIME("Firework Star Lime", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_PINK("Firework Star Pink", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_GRAY("Firework Star Gray", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_LIGHT_GRAY("Firework Star Light Gray", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_CYAN("Firework Star Cyan", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_PURPLE("Firework Star Purple", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_BLUE("Firework Star Blue", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_BROWN("Firework Star Brown", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_GREEN("Firework Star Green", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_RED("Firework Star Red", Dimension.OVERWORLD, 2),
	FIREWORK_STAR_BLACK("Firework Star Black", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_WHITE("Firework Rocket White", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_ORANGE("Firework Rocket Orange", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_MAGENTA("Firework Rocket Magenta", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_LIGHT_BLUE("Firework Rocket Light Blue", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_YELLOW("Firework Rocket Yellow", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_LIME("Firework Rocket Lime", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_PINK("Firework Rocket Pink", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_GRAY("Firework Rocket Gray", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_LIGHT_GRAY("Firework Rocket Light Gray", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_CYAN("Firework Rocket Cyan", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_PURPLE("Firework Rocket Purple", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_BLUE("Firework Rocket Blue", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_BROWN("Firework Rocket Brown", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_GREEN("Firework Rocket Green", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_RED("Fireworld Rocket Red", Dimension.OVERWORLD, 2),
	FIREWORK_ROCKET_BLACK("Firework Rocket Black", Dimension.OVERWORLD, 2),
	SHIELD("Shield", Dimension.OVERWORLD, 2),
	CROSSBOW("Crossbow", Dimension.OVERWORLD, 2),
	BOW("Bow", Dimension.OVERWORLD, 2),
	MAP_EMPTY("Empty Map", Dimension.OVERWORLD, 2),
	FILLED_MAP("Map", Dimension.OVERWORLD, 2),
	POTION_OF_REGENERATION("Potion of Regeneration", Dimension.OVERWORLD, 2),
	POTION_OF_REGENERATION_II("Potion of Regeneration II", Dimension.OVERWORLD, 2),
	POTION_OF_SWIFTNESS("Potion of Swiftness", Dimension.OVERWORLD, 2),
	POTION_OF_SWIFTNESS_II("Potion of Swiftness II", Dimension.OVERWORLD, 2),
	POTION_OF_FIRE_RESISTANCE("Potion of Fire Resistance", Dimension.OVERWORLD, 2),
	POTION_OF_HEALING("Potion of Healing", Dimension.OVERWORLD, 2),
	POTION_OF_HEALING_II("Potion of Healing II", Dimension.OVERWORLD, 2),
	POTION_OF_NIGHT_VISION("Potion of Night Vision", Dimension.OVERWORLD, 2),
	POTION_OF_STRENGTH("Potion of Strength", Dimension.OVERWORLD, 2),
	POTION_OF_STRENGTH_II("Potion of Strength II", Dimension.OVERWORLD, 2),
	POTION_OF_LEAPING("Potion of Leaping", Dimension.OVERWORLD, 2),
	POTION_OF_LEAPING_II("Potion of Leaping II", Dimension.OVERWORLD, 2),
	POTION_OF_WATER_BREATHING("Potion of Water Breathing", Dimension.OVERWORLD, 2),
	POTION_OF_INVISIBILITY("Potion of Invisibility", Dimension.OVERWORLD, 2),
	POTION_OF_SLOW_FALLING("Potion of Slow Falling", Dimension.OVERWORLD, 2),
	POTION_OF_POISON("Potion of Poison", Dimension.OVERWORLD, 2),
	POTION_OF_POISON_II("Potion of Poison II", Dimension.OVERWORLD, 2),
	POTION_OF_WEAKNESS("Potion of Weakness", Dimension.OVERWORLD, 2),
	POTION_OF_SLOWNESS("Potion of Slowness", Dimension.OVERWORLD, 2),
	POTION_OF_SLOWNESS_IV("Potion of Slowness IV", Dimension.OVERWORLD, 2),
	POTION_OF_HARMING("Potion of Harming", Dimension.OVERWORLD, 2),
	POTION_OF_HARMING_II("Potion of Harming II", Dimension.OVERWORLD, 2),
	POTION_OF_THE_TURTLE_MASTER("Potion of the Turtle Master", Dimension.OVERWORLD, 2),
	POTION_OF_THE_TURTLE_MASTER_II("Potion of the Turtle Master II", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_REGENERATION("Splash Potion of Regeneration", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_REGENERATION_II("Splash Potion of Regeneration II", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_SWIFTNESS("Splash Potion of Swiftness", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_SWIFTNESS_II("Splash Potion of Swiftness II", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_FIRE_RESISTANCE("Splash Potion of Fire Resistance", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_HEALING("Splash Potion of Healing", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_HEALING_II("Splash Potion of Healing II", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_NIGHT_VISION("Splash Potion of Night Vision", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_STRENGTH("Splash Potion of Strength", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_STRENGTH_II("Splash Potion of Strength II", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_LEAPING("Splash Potion of Leaping", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_LEAPING_II("Splash Potion of Leaping II", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_WATER_BREATHING("Splash Potion of Water Breathing", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_INVISIBILITY("Splash Potion of Invisibility", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_SLOW_FALLING("Splash Potion of Slow Falling", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_POISON("Splash Potion of Poison", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_POISON_II("Splash Potion of Poison II", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_WEAKNESS("Splash Potion of Weakness", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_SLOWNESS("Splash Potion of Slowness", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_SLOWNESS_IV("Splash Potion of Slowness IV", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_HARMING("Splash Potion of Harming", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_HARMING_II("Splash Potion of Harming II", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_THE_TURTLE_MASTER("Splash Potion of the Turtle Master", Dimension.OVERWORLD, 2),
	SPLASH_POTION_OF_THE_TURTLE_MASTER_II("Splash Potion of the Turtle Master II", Dimension.OVERWORLD, 2),
	ARROW_OF_FIRE_RESISTANCE("Arrow of Fire Resistance", Dimension.OVERWORLD, 2),
	ARROW_OF_HARMING("Arrow of Harming", Dimension.OVERWORLD, 2),
	ARROW_OF_HARMING_II("Arrow of Harming II", Dimension.OVERWORLD, 2),
	ARROW_OF_HEALING("Arrow of Healing", Dimension.OVERWORLD, 2),
	ARROW_OF_HEALING_II("Arrow of Healing II", Dimension.OVERWORLD, 2),
	ARROW_OF_INVISIBILITY("Arrow of Invisibility", Dimension.OVERWORLD, 2),
	ARROW_OF_LEAPING("Arrow of Leaping", Dimension.OVERWORLD, 2),
	ARROW_OF_LEAPING_II("Arrow of Leaping II", Dimension.OVERWORLD, 2),
	ARROW_OF_NIGHT_VISION("Arrow of Night Vision", Dimension.OVERWORLD, 2),
	ARROW_OF_POISON("Arrow of Poison", Dimension.OVERWORLD, 2),
	ARROW_OF_POISON_II("Arrow of Poison II", Dimension.OVERWORLD, 2),
	ARROW_OF_REGENERATION("Arrow of Regeneration", Dimension.OVERWORLD, 2),
	ARROW_OF_REGENERATION_II("Arrow of Regeneration II", Dimension.OVERWORLD, 2),
	ARROW_OF_SLOW_FALLING("Arrow of Slow Falling", Dimension.OVERWORLD, 2),
	ARROW_OF_SLOWNESS("Arrow of Slowness", Dimension.OVERWORLD, 2),
	ARROW_OF_SLOWNESS_IV("Arrow of Slowness IV", Dimension.OVERWORLD, 2),
	ARROW_OF_STRENGTH("Arrow of Strength", Dimension.OVERWORLD, 2),
	ARROW_OF_STRENGTH_II("Arrow of Strength II", Dimension.OVERWORLD, 2),
	ARROW_OF_SWIFTNESS("Arrow of Swiftness", Dimension.OVERWORLD, 2),
	ARROW_OF_SWIFTNESS_II("Arrow of Swiftness II", Dimension.OVERWORLD, 2),
	ARROW_OF_THE_TURTLE_MASTER("Arrow of the Turtle Master", Dimension.OVERWORLD, 2),
	ARROW_OF_THE_TURTLE_MASTER_II("Arrow of the Turtle Master II", Dimension.OVERWORLD, 2),
	ARROW_OF_WATER_BREATHING("Arrow of Water Breathing", Dimension.OVERWORLD, 2),
	ARROW_OF_WEAKNESS("Arrow of Weakness", Dimension.OVERWORLD, 2),
	SPECTRAL_ARROW("Spectral Arrow", Dimension.OVERWORLD, 2),
	TIPPED_ARROW_AWKWARD("Tipped Arrow (Awkward)", Dimension.OVERWORLD, 2),
	TIPPED_ARROW_MUNDANE("Tipped Arrow (Mundane)", Dimension.OVERWORLD, 2),
	TIPPED_ARROW_THICK("Tipped Arrow (Thick)", Dimension.OVERWORLD, 2),
	SPLASH_WATER_BOTTLE("Splash Water Bottle", Dimension.OVERWORLD, 2),
	SPLASH_AWKWARD_POTION("Splash Awkward Potion", Dimension.OVERWORLD, 2),
	SPLASH_MUNDANE_POTION("Splash Mundane Potion", Dimension.OVERWORLD, 2),
	SPLASH_THICK_POTION("Splash Thick Potion", Dimension.OVERWORLD, 2),
	MINECART_WITH_FURNACE("Minecart with Furnace", Dimension.OVERWORLD, 2),
	BOOK_AND_QUILL("Book and Quill", Dimension.OVERWORLD, 2),
	WRITTEN_BOOK("Written Book", Dimension.OVERWORLD, 2),
	TURTLE_EGG("Turtle Egg", Dimension.OVERWORLD, 2),
	TURTLE_SCUTE("Turtle Scute", Dimension.OVERWORLD, 2),
	TURTLE_SHELL("Turtle Shell", Dimension.OVERWORLD, 2),
	ARMADILLO_SCUTE("Armadillo Scute", Dimension.OVERWORLD, 2),
	CONDUIT("Conduit", Dimension.OVERWORLD, 2),
	HEART_OF_THE_SEA("Heart of the Sea", Dimension.OVERWORLD, 2),
	SEA_LANTERN("Sea Lantern", Dimension.OVERWORLD, 2),
	PRISMARINE_SHARD("Prismarine Shard", Dimension.OVERWORLD, 2),
	PRISMARINE_CRYSTALS("Prismarine Crystals", Dimension.OVERWORLD, 2),
	PRISMARINE("Prismarine", Dimension.OVERWORLD, 2),
	PRISMARINE_BRICKS("Prismarine Bricks", Dimension.OVERWORLD, 2),
	DARK_PRISMARINE("Dark Prismarine", Dimension.OVERWORLD, 2),
	PRISMARINE_SLAB("Prismarine Slab", Dimension.OVERWORLD, 2),
	PRISMARINE_STAIRS("Prismarine Stairs", Dimension.OVERWORLD, 2),
	PRISMARINE_WALL("Prismarine Wall", Dimension.OVERWORLD, 2),
	PRISMARINE_BRICK_SLAB("Prismarine Brick Slab", Dimension.OVERWORLD, 2),
	PRISMARINE_BRICK_STAIRS("Prismarine Brick Stairs", Dimension.OVERWORLD, 2),
	DARK_PRISMARINE_SLAB("Dark Prismarine Slab", Dimension.OVERWORLD, 2),
	DARK_PRISMARINE_STAIRS("Dark Prismarine Stairs", Dimension.OVERWORLD, 2),
	GLOW_BERRIES("Glow Berries", Dimension.OVERWORLD, 2),
	GLOW_INK_SAC("Glow Ink Sac", Dimension.OVERWORLD, 2),
	AXOLOTL_BUCKET("Bucket of Axolotl", Dimension.OVERWORLD, 2),
	COD_BUCKET("Bucket of Cod", Dimension.OVERWORLD, 2),
	PUFFERFISH_BUCKET("Bucket of Pufferfish", Dimension.OVERWORLD, 2),
	SALMON_BUCKET("Bucket of Salmon", Dimension.OVERWORLD, 2),
	TADPOLE_BUCKET("Bucket of Tadpole", Dimension.OVERWORLD, 2),
	TROPICAL_FISH_BUCKET("Bucket of Tropical Fish", Dimension.OVERWORLD, 2),
	OCHRE_FROGLIGHT("Ochre Froglight", Dimension.OVERWORLD, 2),
	VERDANT_FROGLIGHT("Verdant Froglight", Dimension.OVERWORLD, 2),
	PEARLESCENT_FROGLIGHT("Pearlescent Froglight", Dimension.OVERWORLD, 2),
	WAXED_BLOCK_OF_COPPER("Waxed Block of Copper", Dimension.OVERWORLD, 2),
	WAXED_CUT_COPPER("Waxed Cut Copper", Dimension.OVERWORLD, 2),
	WAXED_CUT_COPPER_SLAB("Waxed Cut Copper Slab", Dimension.OVERWORLD, 2),
	WAXED_CUT_COPPER_STAIRS("Waxed Cut Copper Stairs", Dimension.OVERWORLD, 2),
	WAXED_COPPER_GRATE("Waxed Copper Grate", Dimension.OVERWORLD, 2),
	WAXED_COPPER_DOOR("Waxed Copper Door", Dimension.OVERWORLD, 2),
	WAXED_COPPER_TRAPDOOR("Waxed Copper Trapdoor", Dimension.OVERWORLD, 2),
	WAXED_COPPER_BULB("Waxed Copper Bulb", Dimension.OVERWORLD, 2),
	WAXED_EXPOSED_COPPER("Waxed Exposed Copper", Dimension.OVERWORLD, 2),
	WAXED_EXPOSED_CUT_COPPER("Waxed Exposed Cut Copper", Dimension.OVERWORLD, 2),
	WAXED_EXPOSED_CUT_COPPER_SLAB("Waxed Exposed Cut Copper Slab", Dimension.OVERWORLD, 2),
	WAXED_EXPOSED_CUT_COPPER_STAIRS("Waxed Exposed Cut Copper Stairs", Dimension.OVERWORLD, 2),
	WAXED_EXPOSED_COPPER_GRATE("Waxed Exposed Copper Grate", Dimension.OVERWORLD, 2),
	WAXED_EXPOSED_COPPER_DOOR("Waxed Exposed Copper Door", Dimension.OVERWORLD, 2),
	WAXED_EXPOSED_COPPER_TRAPDOOR("Waxed Exposed Copper Trapdoor", Dimension.OVERWORLD, 2),
	WAXED_EXPOSED_COPPER_BULB("Waxed Exposed Copper Bulb", Dimension.OVERWORLD, 2),
	WAXED_WEATHERED_COPPER("Waxed Weathered Copper", Dimension.OVERWORLD, 2),
	WAXED_WEATHERED_CUT_COPPER("Waxed Weathered Cut Copper", Dimension.OVERWORLD, 2),
	WAXED_WEATHERED_CUT_COPPER_SLAB("Waxed Weathered Cut Copper Slab", Dimension.OVERWORLD, 2),
	WAXED_WEATHERED_CUT_COPPER_STAIRS("Waxed Weathered Cut Copper Stairs", Dimension.OVERWORLD, 2),
	WAXED_WEATHERED_COPPER_GRATE("Waxed Weathered Copper Grate", Dimension.OVERWORLD, 2),
	WAXED_WEATHERED_COPPER_DOOR("Waxed Weathered Copper Door", Dimension.OVERWORLD, 2),
	WAXED_WEATHERED_COPPER_TRAPDOOR("Waxed Weathered Copper Trapdoor", Dimension.OVERWORLD, 2),
	WAXED_WEATHERED_COPPER_BULB("Waxed Weathered Copper Bulb", Dimension.OVERWORLD, 2),
	WAXED_OXIDIZED_COPPER("Waxed Oxidized Copper", Dimension.OVERWORLD, 2),
	WAXED_OXIDIZED_CUT_COPPER("Waxed Oxidized Cut Copper", Dimension.OVERWORLD, 2),
	WAXED_OXIDIZED_CUT_COPPER_SLAB("Waxed Oxidized Cut Copper Slab", Dimension.OVERWORLD, 2),
	WAXED_OXIDIZED_CUT_COPPER_STAIRS("Waxed Oxidized Cut Copper Stairs", Dimension.OVERWORLD, 2),
	WAXED_OXIDIZED_COPPER_GRATE("Waxed Oxidized Copper Grate", Dimension.OVERWORLD, 2),
	WAXED_OXIDIZED_COPPER_DOOR("Waxed Oxidized Copper Door", Dimension.OVERWORLD, 2),
	WAXED_OXIDIZED_COPPER_TRAPDOOR("Waxed Oxidized Copper Trapdoor", Dimension.OVERWORLD, 2),
	WAXED_OXIDIZED_COPPER_BULB("Waxed Oxidized Copper Bulb", Dimension.OVERWORLD, 2),
	WAXED_CHISELED_COPPER("Waxed Chiseled Copper", Dimension.OVERWORLD, 2),
	WAXED_EXPOSED_CHISELED_COPPER("Waxed Exposed Chiseled Copper", Dimension.OVERWORLD, 2),
	WAXED_WEATHERED_CHISELED_COPPER("Waxed Weathered Chiseled Copper", Dimension.OVERWORLD, 2),
	WAXED_OXIDIZED_CHISELED_COPPER("Waxed Oxidized Chiseled Copper", Dimension.OVERWORLD, 2),
	TRIDENT("Trident", Dimension.OVERWORLD, 2),
	WOLF_ARMOR("Wolf Armor", Dimension.OVERWORLD, 2),

	GOLDEN_APPLE_ENCHANTED("Enchanted Golden Apple", Dimension.OVERWORLD, 3), // Dupe, keeping it here as it's truly high difficulty
	DIAMOND_HELMET_ENCHANTED("Diamond Helmet (Enchanted)", Dimension.OVERWORLD, 3),
	DIAMOND_CHESTPLATE_ENCHANTED("Diamond Chestplate (Enchanted)", Dimension.OVERWORLD, 3),
	DIAMOND_LEGGINGS_ENCHANTED("Diamond Leggings (Enchanted)", Dimension.OVERWORLD, 3),
	DIAMOND_BOOTS_ENCHANTED("Diamond Boots (Enchanted)", Dimension.OVERWORLD, 3),
	DIAMOND_SWORD_ENCHANTED("Diamond Sword (Enchanted)", Dimension.OVERWORLD, 3),
	DIAMOND_PICKAXE_ENCHANTED("Diamond Pickaxe (Enchanted)", Dimension.OVERWORLD, 3),
	DIAMOND_AXE_ENCHANTED("Diamond Axe (Enchanted)", Dimension.OVERWORLD, 3),
	DIAMOND_SHOVEL_ENCHANTED("Diamond Shovel (Enchanted)", Dimension.OVERWORLD, 3),
	DIAMOND_HOE_ENCHANTED("Diamond Hoe (Enchanted)", Dimension.OVERWORLD, 3),
	CHAINMAIL_BOOTS("Chainmail Boots", Dimension.OVERWORLD, 3),
	CHAINMAIL_CHESTPLATE("Chainmail Chestplate", Dimension.OVERWORLD, 3),
	CHAINMAIL_HELMET("Chainmail Helmet", Dimension.OVERWORLD, 3),
	CHAINMAIL_LEGGINGS("Chainmail Leggings", Dimension.OVERWORLD, 3),
	PUMPKIN_CARVED("Carved Pumpkin", Dimension.OVERWORLD, 3),
	JACK_O_LANTERN("Jack o'Lantern", Dimension.OVERWORLD, 3),
	MUSIC_DISC_13("Music Disc (13)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_CAT("Music Disc (Cat)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_BLOCKS("Music Disc (Blocks)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_CHIRP("Music Disc (Chirp)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_FAR("Music Disc (Far)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_MALL("Music Disc (Mall)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_MELLOHI("Music Disc (Mellohi)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_STAL("Music Disc (Stal)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_STRAD("Music Disc (Strad)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_WARD("Music Disc (Ward)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_11("Music Disc (11)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_WAIT("Music Disc (Wait)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_OTHERSIDE("Music Disc (Otherside)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_RELIC("Music Disc (Relic)", Dimension.OVERWORLD, 3),
	MUSIC_DISC_5("Music Disc (5)", Dimension.OVERWORLD, 3),
	TRIPWIRE_HOOK("Tripwire Hook", Dimension.OVERWORLD, 3),
	CONDUIT_ITEM("Conduit", Dimension.OVERWORLD, 3), // As crafted item
	SCOUT_ARMOR_TRIM("Scout Armor Trim", Dimension.OVERWORLD, 3), // Assuming from Trail Ruins
	WAYFINDER_ARMOR_TRIM("Wayfinder Armor Trim", Dimension.OVERWORLD, 3), // Assuming from Trail Ruins
	RAISER_ARMOR_TRIM("Raiser Armor Trim", Dimension.OVERWORLD, 3), // Assuming from Trail Ruins
	SHAPER_ARMOR_TRIM("Shaper Armor Trim", Dimension.OVERWORLD, 3), // Assuming from Trail Ruins
	HOST_ARMOR_TRIM("Host Armor Trim", Dimension.OVERWORLD, 3), // Assuming from Trail Ruins
	ANGLER_POTTERY_SHERD("Angler Pottery Sherd", Dimension.OVERWORLD, 3),
	ARCHER_POTTERY_SHERD("Archer Pottery Sherd", Dimension.OVERWORLD, 3),
	ARMS_UP_POTTERY_SHERD("Arms Up Pottery Sherd", Dimension.OVERWORLD, 3),
	BLADE_POTTERY_SHERD("Blade Pottery Sherd", Dimension.OVERWORLD, 3),
	BREWER_POTTERY_SHERD("Brewer Pottery Sherd", Dimension.OVERWORLD, 3),
	BURN_POTTERY_SHERD("Burn Pottery Sherd", Dimension.OVERWORLD, 3),
	DANGER_POTTERY_SHERD("Danger Pottery Sherd", Dimension.OVERWORLD, 3),
	EXPLORER_POTTERY_SHERD("Explorer Pottery Sherd", Dimension.OVERWORLD, 3),
	FLOW_POTTERY_SHERD("Flow Pottery Sherd", Dimension.OVERWORLD, 3),
	FRIEND_POTTERY_SHERD("Friend Pottery Sherd", Dimension.OVERWORLD, 3),
	GUSTER_POTTERY_SHERD("Guster Pottery Sherd", Dimension.OVERWORLD, 3),
	HEART_POTTERY_SHERD("Heart Pottery Sherd", Dimension.OVERWORLD, 3),
	HEARTBREAK_POTTERY_SHERD("Heartbreak Pottery Sherd", Dimension.OVERWORLD, 3),
	HOWL_POTTERY_SHERD("Howl Pottery Sherd", Dimension.OVERWORLD, 3),
	MINER_POTTERY_SHERD("Miner Pottery Sherd", Dimension.OVERWORLD, 3),
	MOURNER_POTTERY_SHERD("Mourner Pottery Sherd", Dimension.OVERWORLD, 3),
	PLENTY_POTTERY_SHERD("Plenty Pottery Sherd", Dimension.OVERWORLD, 3),
	PRIZE_POTTERY_SHERD("Prize Pottery Sherd", Dimension.OVERWORLD, 3),
	SCRAPE_POTTERY_SHERD("Scrape Pottery Sherd", Dimension.OVERWORLD, 3),
	SHEAF_POTTERY_SHERD("Sheaf Pottery Sherd", Dimension.OVERWORLD, 3),
	SHELTER_POTTERY_SHERD("Shelter Pottery Sherd", Dimension.OVERWORLD, 3),
	SKULL_POTTERY_SHERD("Skull Pottery Sherd", Dimension.OVERWORLD, 3),
	SNORT_POTTERY_SHERD("Snort Pottery Sherd", Dimension.OVERWORLD, 3),
	ANGLER_DECORATED_POT("Angler Decorated Pot", Dimension.OVERWORLD, 3),
	ARCHER_DECORATED_POT("Archer Decorated Pot", Dimension.OVERWORLD, 3),
	ARMS_UP_DECORATED_POT("Arms Up Decorated Pot", Dimension.OVERWORLD, 3),
	BLADE_DECORATED_POT("Blade Decorated Pot", Dimension.OVERWORLD, 3),
	BREWER_DECORATED_POT("Brewer Decorated Pot", Dimension.OVERWORLD, 3),
	BURN_DECORATED_POT("Burn Decorated Pot", Dimension.OVERWORLD, 3),
	DANGER_DECORATED_POT("Danger Decorated Pot", Dimension.OVERWORLD, 3),
	EXPLORER_DECORATED_POT("Explorer Decorated Pot", Dimension.OVERWORLD, 3),
	FLOW_DECORATED_POT("Flow Decorated Pot", Dimension.OVERWORLD, 3),
	FRIEND_DECORATED_POT("Friend Decorated Pot", Dimension.OVERWORLD, 3),
	GUSTER_DECORATED_POT("Guster Decorated Pot", Dimension.OVERWORLD, 3),
	HEART_DECORATED_POT("Heart Decorated Pot", Dimension.OVERWORLD, 3),
	HEARTBREAK_DECORATED_POT("Heartbreak Decorated Pot", Dimension.OVERWORLD, 3),
	HOWL_DECORATED_POT("Howl Decorated Pot", Dimension.OVERWORLD, 3),
	MINER_DECORATED_POT("Miner Decorated Pot", Dimension.OVERWORLD, 3),
	MOURNER_DECORATED_POT("Mourner Decorated Pot", Dimension.OVERWORLD, 3),
	PLENTY_DECORATED_POT("Plenty Decorated Pot", Dimension.OVERWORLD, 3),
	PRIZE_DECORATED_POT("Prize Decorated Pot", Dimension.OVERWORLD, 3),
	SCRAPE_DECORATED_POT("Scrape Decorated Pot", Dimension.OVERWORLD, 3),
	SHEAF_DECORATED_POT("Sheaf Decorated Pot", Dimension.OVERWORLD, 3),
	SHELTER_DECORATED_POT("Shelter Decorated Pot", Dimension.OVERWORLD, 3),
	SKULL_DECORATED_POT("Skull Decorated Pot", Dimension.OVERWORLD, 3),
	SNORT_DECORATED_POT("Snort Decorated Pot", Dimension.OVERWORLD, 3),
	BRUSH("Brush", Dimension.OVERWORLD, 3),
	RECOVERY_COMPASS("Recovery Compass", Dimension.OVERWORLD, 3),
	ECHO_SHARD("Echo Shard", Dimension.OVERWORLD, 3),
	CALIBRATED_SCULK_SENSOR("Calibrated Sculk Sensor", Dimension.OVERWORLD, 3),
	TRIAL_KEY("Trial Key", Dimension.OVERWORLD, 3),
	OMINOUS_BOTTLE("Ominous Bottle", Dimension.OVERWORLD, 3),
	WIND_CHARGE("Wind Charge", Dimension.OVERWORLD, 3),
	MACE("Mace", Dimension.OVERWORLD, 3),

	ANVIL("Anvil", Dimension.OVERWORLD, 4),
	CHIPPED_ANVIL("Chipped Anvil", Dimension.OVERWORLD, 4),
	DAMAGED_ANVIL("Damaged Anvil", Dimension.OVERWORLD, 4),
	BEACON("Beacon", Dimension.OVERWORLD, 4),
	GHAST_TEAR("Ghast Tear", Dimension.OVERWORLD, 4), // Dropped by Ghasts, relatively rare
	SHULKER_BOX_BLACK("Black Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_BLUE("Blue Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_BROWN("Brown Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_CYAN("Cyan Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_GRAY("Gray Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_GREEN("Green Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_LIGHT_BLUE("Light Blue Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_LIGHT_GRAY("Light Gray Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_LIME("Lime Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_MAGENTA("Magenta Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_ORANGE("Orange Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_PINK("Pink Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_PURPLE("Purple Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_RED("Red Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_WHITE("White Shulker Box", Dimension.OVERWORLD, 4),
	SHULKER_BOX_YELLOW("Yellow Shulker Box", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_AQUA_AFFINITY_I("Enchanted Book (Aqua Affinity I)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_BANE_OF_ARTHROPODS_V("Enchanted Book (Bane of Arthropods V)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_BLAST_PROTECTION_IV("Enchanted Book (Blast Protection IV)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_CHANNELING_I("Enchanted Book (Channeling I)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_CURSE_OF_BINDING_I("Enchanted Book (Curse of Binding I)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_CURSE_OF_VANISHING_I("Enchanted Book (Curse of Vanishing I)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_DEPTH_STRIDER_III("Enchanted Book (Depth Strider III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_EFFICIENCY_V("Enchanted Book (Efficiency V)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_FEATHER_FALLING_IV("Enchanted Book (Feather Falling IV)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_FIRE_ASPECT_II("Enchanted Book (Fire Aspect II)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_FIRE_PROTECTION_IV("Enchanted Book (Fire Protection IV)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_FLAME_I("Enchanted Book (Flame I)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_FORTUNE_III("Enchanted Book (Fortune III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_FROST_WALKER_II("Enchanted Book (Frost Walker II)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_IMPALING_V("Enchanted Book (Impaling V)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_INFINITY_I("Enchanted Book (Infinity I)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_KNOCKBACK_II("Enchanted Book (Knockback II)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_LOOTING_III("Enchanted Book (Looting III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_LOYALTY_III("Enchanted Book (Loyalty III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_LUCK_OF_THE_SEA_III("Enchanted Book (Luck of the Sea III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_LURE_III("Enchanted Book (Lure III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_MENDING_I("Enchanted Book (Mending I)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_MULTISHOT_I("Enchanted Book (Multishot I)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_PIERCING_IV("Enchanted Book (Piercing IV)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_POWER_V("Enchanted Book (Power V)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_PROJECTILE_PROTECTION_IV("Enchanted Book (Projectile Protection IV)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_PROTECTION_IV("Enchanted Book (Protection IV)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_PUNCH_II("Enchanted Book (Punch II)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_QUICK_CHARGE_III("Enchanted Book (Quick Charge III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_RESPIRATION_III("Enchanted Book (Respiration III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_RIPTIDE_III("Enchanted Book (Riptide III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_SHARPNESS_V("Enchanted Book (Sharpness V)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_SILK_TOUCH_I("Enchanted Book (Silk Touch I)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_SMITE_V("Enchanted Book (Smite V)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_SOUL_SPEED_III("Enchanted Book (Soul Speed III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_SWEEPING_EDGE_III("Enchanted Book (Sweeping Edge III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_SWIFT_SNEAK_III("Enchanted Book (Swift Sneak III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_THORNS_III("Enchanted Book (Thorns III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_UNBREAKING_III("Enchanted Book (Unbreaking III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_WIND_BURST_III("Enchanted Book (Wind Burst III)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_BREACH_IV("Enchanted Book (Breach IV)", Dimension.OVERWORLD, 4),
	ENCHANTED_BOOK_DENSITY_V("Enchanted Book (Density V)", Dimension.OVERWORLD, 4),
	BURIED_TREASURE_MAP("Buried Treasure Map", Dimension.OVERWORLD, 4),
	DESERT_VILLAGE_MAP("Desert Village Map", Dimension.OVERWORLD, 4),
	JUNGLE_EXPLORER_MAP("Jungle Explorer Map", Dimension.OVERWORLD, 4),
	OCEAN_EXPLORER_MAP("Ocean Explorer Map", Dimension.OVERWORLD, 4),
	PLAINS_VILLAGE_MAP("Plains Village Map", Dimension.OVERWORLD, 4),
	SAVANNA_VILLAGE_MAP("Savanna Village Map", Dimension.OVERWORLD, 4),
	SNOWY_VILLAGE_MAP("Snowy Village Map", Dimension.OVERWORLD, 4),
	SWAMP_EXPLORER_MAP("Swamp Explorer Map", Dimension.OVERWORLD, 4),
	TAIGA_VILLAGE_MAP("Taiga Village Map", Dimension.OVERWORLD, 4),
	TRIAL_EXPLORER_MAP("Trial Explorer Map", Dimension.OVERWORLD, 4),
	WOODLAND_EXPLORER_MAP("Woodland Explorer Map", Dimension.OVERWORLD, 4),
	NAME_TAG("Name Tag", Dimension.OVERWORLD, 4),
	MUSIC_DISC_PIGSTEP("Music Disc (Pigstep)", Dimension.OVERWORLD, 4),
	SCULK_SENSOR("Sculk Sensor", Dimension.OVERWORLD, 4),
	SCULK_CATALYST("Sculk Catalyst", Dimension.OVERWORLD, 4),
	SCULK_SHRIEKER("Sculk Shrieker", Dimension.OVERWORLD, 4),
	OMINOUS_BANNER("Ominous Banner", Dimension.OVERWORLD, 4),
	WIND_CHARGE_ITEM("Wind Charge", Dimension.OVERWORLD, 4), // As the dropped item from Breeze
	BREEZE_ROD("Breeze Rod", Dimension.OVERWORLD, 4),
	HEAVY_CORE("Heavy Core", Dimension.OVERWORLD, 4),
	CREAKING_HEART("Creaking Heart", Dimension.OVERWORLD, 4),

	// Nether
	NETHERRACK("Netherrack", Dimension.NETHER, 0),
	CRIMSON_NYLIUM("Crimson Nylium", Dimension.NETHER, 0),
	WARPED_NYLIUM("Warped Nylium", Dimension.NETHER, 0),
	CRIMSON_FUNGUS("Crimson Fungus", Dimension.NETHER, 0),
	WARPED_FUNGUS("Warped Fungus", Dimension.NETHER, 0),
	CRIMSON_ROOTS("Crimson Roots", Dimension.NETHER, 0),
	WARPED_ROOTS("Warped Roots", Dimension.NETHER, 0),
	NETHER_SPROUTS("Nether Sprouts", Dimension.NETHER, 0),
	WARPED_WART_BLOCK("Warped Wart Block", Dimension.NETHER, 0),
	CRIMSON_STEM("Crimson Stem", Dimension.NETHER, 0),
	WARPED_STEM("Warped Stem", Dimension.NETHER, 0),
	CRIMSON_HYPHAE("Crimson Hyphae", Dimension.NETHER, 0),
	WARPED_HYPHAE("Warped Hyphae", Dimension.NETHER, 0),
	CRIMSON_PLANKS("Crimson Planks", Dimension.NETHER, 0),
	WARPED_PLANKS("Warped Planks", Dimension.NETHER, 0),
	CRIMSON_SLAB("Crimson Slab", Dimension.NETHER, 0),
	WARPED_SLAB("Warped Slab", Dimension.NETHER, 0),
	CRIMSON_STAIRS("Crimson Stairs", Dimension.NETHER, 0),
	WARPED_STAIRS("Warped Stairs", Dimension.NETHER, 0),
	CRIMSON_FENCE("Crimson Fence", Dimension.NETHER, 0),
	WARPED_FENCE("Warped Fence", Dimension.NETHER, 0),
	CRIMSON_FENCE_GATE("Crimson Fence Gate", Dimension.NETHER, 0),
	WARPED_FENCE_GATE("Warped Fence Gate", Dimension.NETHER, 0),
	CRIMSON_DOOR("Crimson Door", Dimension.NETHER, 0),
	WARPED_DOOR("Warped Door", Dimension.NETHER, 0),
	CRIMSON_TRAPDOOR("Crimson Trapdoor", Dimension.NETHER, 0),
	WARPED_TRAPDOOR("Warped Trapdoor", Dimension.NETHER, 0),
	CRIMSON_BUTTON("Crimson Button", Dimension.NETHER, 0),
	WARPED_BUTTON("Warped Button", Dimension.NETHER, 0),
	CRIMSON_PRESSURE_PLATE("Crimson Pressure Plate", Dimension.NETHER, 0),
	WARPED_PRESSURE_PLATE("Warped Pressure Plate", Dimension.NETHER, 0),
	CRIMSON_SIGN("Crimson Sign", Dimension.NETHER, 0),
	WARPED_SIGN("Warped Sign", Dimension.NETHER, 0),
	CRIMSON_HANGING_SIGN("Crimson Hanging Sign", Dimension.NETHER, 0),
	WARPED_HANGING_SIGN("Warped Hanging Sign", Dimension.NETHER, 0),
	STRIPPED_CRIMSON_STEM("Stripped Crimson Stem", Dimension.NETHER, 0),
	STRIPPED_WARPED_STEM("Stripped Warped Stem", Dimension.NETHER, 0),
	STRIPPED_CRIMSON_HYPHAE("Stripped Crimson Hyphae", Dimension.NETHER, 0),
	STRIPPED_WARPED_HYPHAE("Stripped Warped Hyphae", Dimension.NETHER, 0),
	BLACKSTONE("Blackstone", Dimension.NETHER, 0),
	GILDED_BLACKSTONE("Gilded Blackstone", Dimension.NETHER, 0),
	POLISHED_BLACKSTONE("Polished Blackstone", Dimension.NETHER, 0),
	POLISHED_BLACKSTONE_SLAB("Polished Blackstone Slab", Dimension.NETHER, 0),
	POLISHED_BLACKSTONE_STAIRS("Polished Blackstone Stairs", Dimension.NETHER, 0),
	POLISHED_BLACKSTONE_WALL("Polished Blackstone Wall", Dimension.NETHER, 0),
	POLISHED_BLACKSTONE_BUTTON("Polished Blackstone Button", Dimension.NETHER, 0),
	POLISHED_BLACKSTONE_PRESSURE_PLATE("Polished Blackstone Pressure Plate", Dimension.NETHER, 0),
	POLISHED_BLACKSTONE_BRICKS("Polished Blackstone Bricks", Dimension.NETHER, 0),
	POLISHED_BLACKSTONE_BRICK_SLAB("Polished Blackstone Brick Slab", Dimension.NETHER, 0),
	POLISHED_BLACKSTONE_BRICK_STAIRS("Polished Blackstone Brick Stairs", Dimension.NETHER, 0),
	POLISHED_BLACKSTONE_BRICK_WALL("Polished Blackstone Brick Wall", Dimension.NETHER, 0),
	CRACKED_POLISHED_BLACKSTONE_BRICKS("Cracked Polished Blackstone Bricks", Dimension.NETHER, 0),
	CHISELED_POLISHED_BLACKSTONE("Chiseled Polished Blackstone", Dimension.NETHER, 0),
	BASALT("Basalt", Dimension.NETHER, 0),
	SMOOTH_BASALT("Smooth Basalt", Dimension.NETHER, 0),
	SOUL_SAND("Soul Sand", Dimension.NETHER, 0),
	SOUL_SOIL("Soul Soil", Dimension.NETHER, 0),
	MAGMA_BLOCK("Magma Block", Dimension.NETHER, 0),
	NETHER_BRICKS("Nether Bricks", Dimension.NETHER, 0),
	NETHER_BRICK_SLAB("Nether Brick Slab", Dimension.NETHER, 0),
	NETHER_BRICK_STAIRS("Nether Brick Stairs", Dimension.NETHER, 0),
	NETHER_BRICK_FENCE("Nether Brick Fence", Dimension.NETHER, 0),
	NETHER_BRICK_WALL("Nether Brick Wall", Dimension.NETHER, 0),
	RED_NETHER_BRICKS("Red Nether Bricks", Dimension.NETHER, 0),
	RED_NETHER_BRICK_SLAB("Red Nether Brick Slab", Dimension.NETHER, 0),
	RED_NETHER_BRICK_STAIRS("Red Nether Brick Stairs", Dimension.NETHER, 0),
	RED_NETHER_BRICK_WALL("Red Nether Brick Wall", Dimension.NETHER, 0),
	CHISELED_NETHER_BRICKS("Chiseled Nether Bricks", Dimension.NETHER, 0),
	CRACKED_NETHER_BRICKS("Cracked Nether Bricks", Dimension.NETHER, 0),
	QUARTZ_BLOCK("Block of Quartz", Dimension.NETHER, 0),
	QUARTZ_PILLAR("Quartz Pillar", Dimension.NETHER, 0),
	QUARTZ_SLAB("Quartz Slab", Dimension.NETHER, 0),
	QUARTZ_STAIRS("Quartz Stairs", Dimension.NETHER, 0),
	CHISELED_QUARTZ_BLOCK("Chiseled Quartz Block", Dimension.NETHER, 0),
	SMOOTH_QUARTZ_BLOCK("Smooth Quartz Block", Dimension.NETHER, 0),
	SMOOTH_QUARTZ_SLAB("Smooth Quartz Slab", Dimension.NETHER, 0),
	SMOOTH_QUARTZ_STAIRS("Smooth Quartz Stairs", Dimension.NETHER, 0),
	NETHER_QUARTZ_ORE("Nether Quartz Ore", Dimension.NETHER, 0),
	NETHER_QUARTZ("Nether Quartz", Dimension.NETHER, 0),
	NETHER_GOLD_ORE("Nether Gold Ore", Dimension.NETHER, 0),
	SOUL_TORCH("Soul Torch", Dimension.NETHER, 0),
	SHROOMLIGHT("Shroomlight", Dimension.NETHER, 0),
	TWISTING_VINES("Twisting Vines", Dimension.NETHER, 0),
	WEEPING_VINES("Weeping Vines", Dimension.NETHER, 0),

	BLAZE_ROD("Blaze Rod", Dimension.NETHER, 1),
	BLAZE_POWDER("Blaze Powder", Dimension.NETHER, 1),
	MAGMA_CREAM("Magma Cream", Dimension.NETHER, 1),
	NETHER_WART("Nether Wart", Dimension.NETHER, 1),
	NETHER_WART_BLOCK("Nether Wart Block", Dimension.NETHER, 1),
	WARPED_FUNGUS_ON_A_STICK("Warped Fungus on a Stick", Dimension.NETHER, 1),
	MUSIC_DISC_PIGSTEP_ITEM("Music Disc (Pigstep)", Dimension.NETHER, 1), // As a drop from Piglin, not craftable

	BREWING_STAND_NETHER("Brewing Stand", Dimension.NETHER, 2), // Found in fortresses
	QUARTZ_BRICKS("Quartz Bricks", Dimension.NETHER, 2),
	BLACKSTONE_SLAB("Blackstone Slab", Dimension.NETHER, 2),
	BLACKSTONE_STAIRS("Blackstone Stairs", Dimension.NETHER, 2),
	BLACKSTONE_WALL("Blackstone Wall", Dimension.NETHER, 2),
	SOUL_SAND_L("Soul Sand", Dimension.NETHER, 2), // As a block used to create Wither
	CRIMSON_FUNGUS_CRAFTED("Crimson Fungus", Dimension.NETHER, 2), // If obtained from planting
	WARPED_FUNGUS_CRAFTED("Warped Fungus", Dimension.NETHER, 2), // If obtained from planting

	GHAST_TEAR_NETHER("Ghast Tear", Dimension.NETHER, 3), // As a rare drop in Nether
	NETHER_BRICK_ITEM("Nether Brick", Dimension.NETHER, 3), // From smelting Netherrack
	NETHERITE_SCRAP("Netherite Scrap", Dimension.NETHER, 3),
	ANCIENT_DEBRIS("Ancient Debris", Dimension.NETHER, 3),
	NETHERITE_INGOT("Netherite Ingot", Dimension.NETHER, 3),
	BLOCK_OF_NETHERITE("Block of Netherite", Dimension.NETHER, 3),
	NETHERITE_SWORD("Netherite Sword", Dimension.NETHER, 3),
	NETHERITE_PICKAXE("Netherite Pickaxe", Dimension.NETHER, 3),
	NETHERITE_AXE("Netherite Axe", Dimension.NETHER, 3),
	NETHERITE_SHOVEL("Netherite Shovel", Dimension.NETHER, 3),
	NETHERITE_HOE("Netherite Hoe", Dimension.NETHER, 3),
	NETHERITE_HELMET("Netherite Helmet", Dimension.NETHER, 3),
	NETHERITE_CHESTPLATE("Netherite Chestplate", Dimension.NETHER, 3),
	NETHERITE_LEGGINGS("Netherite Leggings", Dimension.NETHER, 3),
	NETHERITE_BOOTS("Netherite Boots", Dimension.NETHER, 3),
	MUSIC_DISC_PIGSTEP_BARTER("Music Disc (Pigstep)", Dimension.NETHER, 3), // As a rare barter item
	MUSIC_DISC_OTHERSIDE_BARTER("Music Disc (Otherside)", Dimension.NETHER, 3), // As a rare barter item
	BASTION_REMNANT_MAP("Bastion Remnant Map", Dimension.NETHER, 3), // If this refers to a discovery map
	SNOUT_ARMOR_TRIM("Snout Armor Trim", Dimension.NETHER, 3),
	RIB_ARMOR_TRIM("Rib Armor Trim", Dimension.NETHER, 3),
	NETHERITE_UPGRADE("Netherite Upgrade", Dimension.NETHER, 3),

	NETHER_STAR("Nether Star", Dimension.NETHER, 4),
	BEACON_NETHER("Beacon", Dimension.NETHER, 4), // Requires Nether Star
	WITHER_SKELETON_SKULL("Wither Skeleton Skull", Dimension.NETHER, 4),
	CRYING_OBSIDIAN("Crying Obsidian", Dimension.NETHER, 4),
	RESPAWN_ANCHOR("Respawn Anchor", Dimension.NETHER, 4),
	MUSIC_DISC_PIGSTEP_TREASURE("Music Disc (Pigstep)", Dimension.NETHER, 4), // If obtained from treasure chests
	MUSIC_DISC_RELIC_TREASURE("Music Disc (Relic)", Dimension.NETHER, 4), // If obtained from treasure chests

	// End
	END_STONE("End Stone", Dimension.END, 0),
	CHORUS_FLOWER("Chorus Flower", Dimension.END, 0),
	CHORUS_FRUIT("Chorus Fruit", Dimension.END, 0),
	POPPED_CHORUS_FRUIT("Popped Chorus Fruit", Dimension.END, 0),
	PURPUR_BLOCK("Purpur Block", Dimension.END, 0),
	PURPUR_PILLAR("Purpur Pillar", Dimension.END, 0),
	PURPUR_SLAB("Purpur Slab", Dimension.END, 0),
	PURPUR_STAIRS("Purpur Stairs", Dimension.END, 0),
	END_STONE_BRICKS("End Stone Bricks", Dimension.END, 0),
	END_STONE_BRICK_SLAB("End Stone Brick Slab", Dimension.END, 0),
	END_STONE_BRICK_STAIRS("End Stone Brick Stairs", Dimension.END, 0),
	END_STONE_BRICK_WALL("End Stone Brick Wall", Dimension.END, 0),

	ENDER_PEARL("Ender Pearl", Dimension.END, 1),
	EYE_OF_ENDER("Eye of Ender", Dimension.END, 1),

	ELYTRA("Elytra", Dimension.END, 4),
	SHULKER_SHELL("Shulker Shell", Dimension.END, 4),
	END_CRYSTAL("End Crystal", Dimension.END, 4),
	END_ROD("End Rod", Dimension.END, 4),
	DRAGON_EGG("Dragon Egg", Dimension.END, 4),
	DRAGON_HEAD("Dragon Head", Dimension.END, 4),
	DRAGONS_BREATH("Dragon's Breath", Dimension.END, 4),
	PURPLE_SHULKER_BOX("Purple Shulker Box", Dimension.END, 4), // Crafted in End, requires End materials
	END_STONE_BRICK_WALL_CRAFTED("End Stone Brick Wall", Dimension.END, 4), // Crafted in End
	CHORUS_PLANT("Chorus Plant", Dimension.END, 4), // Requires Dragon fight
	THE_DRAGON_EGG("Dragon Egg", Dimension.END, 4), // Duplicate, but keeping for clarity as primary objective
	SPIRE_ARMOR_TRIM("Spire Armor Trim", Dimension.END, 4),
	TIDE_ARMOR_TRIM("Tide Armor Trim", Dimension.END, 4),
	VEX_ARMOR_TRIM("Vex Armor Trim", Dimension.END, 4),
	WARD_ARMOR_TRIM("Ward Armor Trim", Dimension.END, 4),
	WILD_ARMOR_TRIM("Wild Armor Trim", Dimension.END, 4),
	BOLT_ARMOR_TRIM("Bolt Armor Trim", Dimension.END, 4),
	COAST_ARMOR_TRIM("Coast Armor Trim", Dimension.END, 4),
	DUNE_ARMOR_TRIM("Dune Armor Trim", Dimension.END, 4),
	EYE_ARMOR_TRIM("Eye Armor Trim", Dimension.END, 4),
	FLOW_ARMOR_TRIM("Flow Armor Trim", Dimension.END, 4),
	SILENCE_ARMOR_TRIM("Silence Armor Trim", Dimension.END, 4),
	NETHERITE_UPGRADE_END("Netherite Upgrade", Dimension.END, 4), // Found in End City chests


	// Potions (Awkward, Mundane, Thick are base for other potions)
	WATER_BOTTLE("Water Bottle", Dimension.OVERWORLD, 1),
	AWKWARD_POTION("Awkward Potion", Dimension.OVERWORLD, 2),
	MUNDANE_POTION("Mundane Potion", Dimension.OVERWORLD, 2),
	THICK_POTION("Thick Potion", Dimension.OVERWORLD, 2),

	// Splash Potions (requiring dragon's breath for lingering, so slightly higher than base potions)
	SPLASH_POTION_OF_INFESTATION("Splash Potion of Infestation", Dimension.OVERWORLD, 3),
	SPLASH_POTION_OF_OOZING("Splash Potion of Oozing", Dimension.OVERWORLD, 3),
	SPLASH_POTION_OF_WEAVING("Splash Potion of Weaving", Dimension.OVERWORLD, 3),
	SPLASH_POTION_OF_WIND_CHARGING("Splash Potion of Wind Charging", Dimension.OVERWORLD, 3),

	// Lingering Potions (requiring dragon's breath)
	LINGERING_WATER_BOTTLE("Lingering Water Bottle", Dimension.END, 3),
	LINGERING_AWKWARD_POTION("Lingering Awkward Potion", Dimension.END, 3),
	LINGERING_MUNDANE_POTION("Lingering Mundane Potion", Dimension.END, 3),
	LINGERING_THICK_POTION("Lingering Thick Potion", Dimension.END, 3),
	LINGERING_POTION_OF_REGENERATION("Lingering Potion of Regeneration", Dimension.END, 3),
	LINGERING_POTION_OF_REGENERATION_II("Lingering Potion of Regeneration II", Dimension.END, 3),
	LINGERING_POTION_OF_SWIFTNESS("Lingering Potion of Swiftness", Dimension.END, 3),
	LINGERING_POTION_OF_SWIFTNESS_II("Lingering Potion of Swiftness II", Dimension.END, 3),
	LINGERING_POTION_OF_FIRE_RESISTANCE("Lingering Potion of Fire Resistance", Dimension.END, 3),
	LINGERING_POTION_OF_HEALING("Lingering Potion of Healing", Dimension.END, 3),
	LINGERING_POTION_OF_HEALING_II("Lingering Potion of Healing II", Dimension.END, 3),
	LINGERING_POTION_OF_NIGHT_VISION("Lingering Potion of Night Vision", Dimension.END, 3),
	LINGERING_POTION_OF_STRENGTH("Lingering Potion of Strength", Dimension.END, 3),
	LINGERING_POTION_OF_STRENGTH_II("Lingering Potion of Strength II", Dimension.END, 3),
	LINGERING_POTION_OF_LEAPING("Lingering Potion of Leaping", Dimension.END, 3),
	LINGERING_POTION_OF_LEAPING_II("Lingering Potion of Leaping II", Dimension.END, 3),
	LINGERING_POTION_OF_WATER_BREATHING("Lingering Potion of Water Breathing", Dimension.END, 3),
	LINGERING_POTION_OF_INVISIBILITY("Lingering Potion of Invisibility", Dimension.END, 3),
	LINGERING_POTION_OF_SLOW_FALLING("Lingering Potion of Slow Falling", Dimension.END, 3),
	LINGERING_POTION_OF_POISON("Lingering Potion of Poison", Dimension.END, 3),
	LINGERING_POTION_OF_POISON_II("Lingering Potion of Poison II", Dimension.END, 3),
	LINGERING_POTION_OF_WEAKNESS("Lingering Potion of Weakness", Dimension.END, 3),
	LINGERING_POTION_OF_SLOWNESS("Lingering Potion of Slowness", Dimension.END, 3),
	LINGERING_POTION_OF_SLOWNESS_IV("Lingering Potion of Slowness IV", Dimension.END, 3),
	LINGERING_POTION_OF_HARMING("Lingering Potion of Harming", Dimension.END, 3),
	LINGERING_POTION_OF_HARMING_II("Lingering Potion of Harming II", Dimension.END, 3),
	LINGERING_POTION_OF_THE_TURTLE_MASTER("Lingering Potion of the Turtle Master", Dimension.END, 3),
	LINGERING_POTION_OF_THE_TURTLE_MASTER_II("Lingering Potion of the Turtle Master II", Dimension.END, 3),
	LINGERING_POTION_OF_INFESTATION("Lingering Potion of Infestation", Dimension.END, 3),
	LINGERING_POTION_OF_OOZING("Lingering Potion of Oozing", Dimension.END, 3),
	LINGERING_POTION_OF_WEAVING("Lingering Potion of Weaving", Dimension.END, 3),
	LINGERING_POTION_OF_WIND_CHARGING("Lingering Potion of Wind Charging", Dimension.END, 3),

	// Arrows requiring dragon's breath
	ARROW_OF_INFESTATION("Arrow of Infestation", Dimension.END, 3),
	ARROW_OF_OOZING("Arrow of Oozing", Dimension.END, 3),
	ARROW_OF_WEAVING("Arrow of Weaving", Dimension.END, 3),
	ARROW_OF_WIND_CHARGING("Arrow of Wind Charging", Dimension.END, 3),

	// Generic Shulker Box (purple base)
	SHULKER_BOX("Shulker Box", Dimension.END, 3); // Obtained in the End, requiring Shulker Shells

	private final String name;
	private final Dimension dimension;
	private final int difficulty;

	ItemEntry(String name, Dimension dimension, int difficulty) {
		this.name = name;
		this.dimension = dimension;
		this.difficulty = difficulty;
	}

	public String getName() {
		return name;
	}

	public Dimension getDimension() {
		return dimension;
	}

	public int getDifficulty() {
		return difficulty;
	}

	public enum Dimension {
		OVERWORLD,
		NETHER,
		END
	}

	public static List<ItemEntry> getItemsByDifficultyAndDimension(int minDifficulty, int maxDifficulty, Dimension targetDimension) {
		List<ItemEntry> filteredItems = new ArrayList<>();
		for (ItemEntry item : ItemEntry.values()) {
			if (item.getDimension() == targetDimension &&
					item.getDifficulty() >= minDifficulty &&
					item.getDifficulty() <= maxDifficulty) {
				filteredItems.add(item);
			}
		}

		// Sort within the filtered list by difficulty
		filteredItems.sort(Comparator.comparingInt(ItemEntry::getDifficulty));
		return filteredItems;
	}

	// Utility methods for filtering
	public static ItemEntry[] getItemsByDimension(Dimension dimension) {
		return java.util.Arrays.stream(values())
				.filter(item -> item.getDimension() == dimension)
				.toArray(ItemEntry[]::new);
	}

	public static ItemEntry[] getItemsByDifficulty(int difficulty) {
		return java.util.Arrays.stream(values())
				.filter(item -> item.getDifficulty() == difficulty)
				.toArray(ItemEntry[]::new);
	}

	public static ItemEntry[] getItemsByDimensionAndDifficulty(Dimension dimension, int difficulty) {
		return java.util.Arrays.stream(values())
				.filter(item -> item.getDimension() == dimension && item.getDifficulty() == difficulty)
				.toArray(ItemEntry[]::new);
	}

	// Get random item by criteria
	public static ItemEntry getRandomItem() {
		ItemEntry[] items = values();
		return items[(int) (Math.random() * items.length)];
	}

	public static ItemEntry getRandomItemByDimension(Dimension dimension) {
		ItemEntry[] items = getItemsByDimension(dimension);
		return items.length > 0 ? items[(int) (Math.random() * items.length)] : null;
	}

	public static ItemEntry getRandomItemByDifficulty(int difficulty) {
		ItemEntry[] items = getItemsByDifficulty(difficulty);
		return items.length > 0 ? items[(int) (Math.random() * items.length)] : null;
	}

	public static ItemEntry getRandomItemByDimensionAndDifficulty(Dimension dimension, int difficulty) {
		ItemEntry[] items = getItemsByDimensionAndDifficulty(dimension, difficulty);
		return items.length > 0 ? items[(int) (Math.random() * items.length)] : null;
	}
}